uktrade/great-cms

- .circleci/config.yml
- CHANGELOG.md
This change makes every job in our workflow 15s faster.
We can safely remove it as we don't use `docker` or `docker-compose` commands in any of our jobs.
https://circleci.com/docs/2.0/building-docker-images/#overview
No ticket.
> Remove redundant CircleCI step setup remote docker

- CHANGELOG.md
- core/constants.py
- core/templatetags/personalised_blocks.py
- core/templatetags/video_tags.py
- core/wagtail_hooks.py
- tests/helpers.py
- tests/unit/core/factories.py
- tests/unit/core/test_models.py
- tests/unit/core/test_wagtail_hooks.py
- tests/unit/test_templatetags.py
This changeset adds counting of video duration in the read time of a page.
Given we're already rendering and parsing the HTML page, the most effective solution was simply to annotate the `<video>` blocks with a custom, non-clashing data attribute, which we then pull out of the HTML with BeautifulSoup and add to our `readtime` calculation.
* Have at least one lesson in place - note what the current readtime of it is.
* Add a video to the Media section of the CMS, including a duration in seconds - eg 120
* Edit a lesson and add a video as the Hero block (videos and text in the Personalised content section are ignored for readtime purposes)
* Save that page AS DRAFT.
* Preview the draft and confirm the readtime has generally increased by the equivalent number of minutes
* View the live page …
> GP2-500: Include video duration in read time for the page

- CHANGELOG.md
- core/models.py
- tests/unit/core/test_models.py
* Fix bug where max of two elements in media block was not being enforced
* Improve validation to ensure that a Media node HAS to precede a Text node
> GP2-744 and GP2-745: Improve validation of Case Study body streamfield

- CHANGELOG.md
- core/mixins.py
- core/models.py
- tests/unit/core/factories.py
- tests/unit/core/test_middleware.py
- tests/unit/core/test_models.py
This changeset adds`mixins.AuthenticatedUserRequired` to the base page used for most CMS pages (`CMSGenericPage`) so that, if the user is unauthenticated, they are redirected to the login page.
This also has the (requested/desired) side effect that the existing behaviour upon logout (kill session and reload the same page) now causes a redirect when the page is reloaded. Ideally we'd skip the reload, but given this is is a temporary change, I think it's fine for now)
Note that when a user is redirected to signin, we don't remember where they wanted to go originally. This is not ideal, but tolerable within the AC for this piece.
> GP2-726: Redirect unauthenticated users on CMS pages to the sign-in page

- CHANGELOG.md
- core/templates/core/curated_topic.html
- core/templatetags/content_tags.py
- tests/unit/core/test_templatetags.py
This changeset adds topic-level progress counters beside each topic on a module page / CuratedListPage.
It has to do a bit of extra work to re-count the lessons in the topic, but I thought that was less of a mess than refactoring a chain of two helper functions to pass down the additional data for use in a single place. Say if you disagree! 😄
> GP2-164: Show topic progress beside list of lessons in a module page

- core/blocks.py
- core/templates/core/curated_topic.html
- core/templatetags/content_tags.py
- learn/templates/learn/_lesson_placeholder.html
- learn/templates/learn/curated_list_page.html
- tests/unit/core/factories.py
- tests/unit/core/test_templatetags.py
- tests/unit/core/test_utils.py
- tests/unit/domestic/test_helpers.py
This changeset cleans up use of the `lessons_and_topics` StreamField within the `CuratedListPage.topics` `CuratedTopicBlock`
Still leaving the field on the CuratedListPage because we haven't migrated data yet, but removed from the test factories, because no tests touch CuratedListPage.topics any more \o/
UNSTABLE CODEBASE - MID-REFACTOR
> GP2-884: Cleanup old use of lessons_and_topics streamfield

- core/models.py
- core/utils.py
- domestic/helpers.py
- tests/unit/core/test_templatetags.py
Just some small bits of cleaning up - this is the last change before adding a data migration. After the data migration there will be a changeset to drop redundant fields from CuratedListPag
> GP2-884: Refactor topic modelling -  part five - minor cleanup

- CHANGELOG.md
- learn/templates/learn/detail_page.html
Since the topics refactor DetailPage.get_parent() no longer points to the CuratedListPage, but to a TopicPage instead. This 'works' in that a TopicPage redirects to the CuratedListPage when it's loaded, but it's better/faster to go straight to the CuratedListPage (ie the parent of the parent)
> GP2-959: fix backlink in lesson pages

- CHANGELOG.md
- exportplan/helpers.py
- exportplan/views.py
This changeset makes a minor change to allow the EP links to the lessons to work after the refactor.
It also contains a bugfix - the ExportPlanTargetMarketsResearchView lacked the mixin to know how to get lesson details, but the template seemed to expect it
> GP2-960: EP links to lesson pages (post-refactor)

- CHANGELOG.md
- core/utils.py
We needed to ensure we get the specific CuratedListPage instance when gettin the module for a lesson page, not just the Page superclass instance
> GP2-1021: Bugfix - show current module's masthead image in next lesson panel

- CHANGELOG.md
- core/wagtail_hooks.py
- tests/unit/core/test_wagtail_hooks.py
The issue was that we were only acting on the `after_edit_page` hook and not also the `after_create_page` hook.
Also added broader test coverage.
> GP2-816: Fix setting of lesson readtime so that it gets set if a lesson is immediately published

- CHANGELOG.md
- config/settings.py
- config/utils.py
- requirements.in
- requirements.txt
- requirements_test.txt
- tests/unit/config/test_utils.py
This changeset moves us to 0.6, which supports copying objects that use multi-table inheritance, and also handles copying tags on items.
It also reduces the scope of the configuration so that no sites can pull content from Beta, because - for now - we're going to get WT in use up to staging, and then see what extra features we need to support before we can use it to suit our workflows
> GP2-741: Bump Wagtail Transfer to latest version + update config

- CHANGELOG.md
- cms_extras/admin.py
- cms_extras/apps.py
- cms_extras/modeladmin.py
- cms_extras/models.py
- cms_extras/templates/view_case_study.html
- cms_extras/tests.py
- cms_extras/urls.py
- cms_extras/views.py
- config/settings.py
- config/urls.py
- core/models.py
- core/wagtail_hooks.py
- tests/unit/cms_extra/test_modeladmin.py
- tests/unit/cms_extra/test_views.py
- tests/unit/core/test_wagtail_hooks.py
This changeset adds a way to view a case study to the CMS, so that you editors can view them in isolation, without having to create a suitable user in order to match the Case Study's HS or country codes.
* Custom button on the ModelAdmin list page for Case Study that opens that view.
* View renders page which renders only the Case Study component for the selected Case Study - uses official CSS and JS from public site and the same template partial
**List view has a new button**
**CS view starts collapsed and has back-link to list**
**Case study expands/behaves as in the main lesson**
(note that my example image to the right is the wrong size - that's just dummy/test data, not a code bug)
> GP2-901: Case study preview

- CHANGELOG.md
- core/constants.py
- core/wagtail_hooks.py
- tests/unit/core/test_wagtail_hooks.py
Takes the approach of a custom FileAdapter that is only used if all assets are on S3.
Key points:
* Uses the hash of the file from the S3 ETag rather than load and hash the entire file - saves time. See the comments re the use of the ETag as a hash: there are some limitations.
* Uses S3's client.copy() API to do the copying legwork, rather than "download, stream accross, upload" - saves time
* ONLY works if the source file is publicly readable
* ONLY works within the same AWS Region (according to the docs - untested)
> GP2-661: Support S3-to-S3 copying for Wagtail Transfer

- config/urls.py
- tests/unit/cms_extra/test_modeladmin.py
- tests/unit/cms_extra/test_views.py
* Just changes the cms_extras app to be clearly below `/admin/` in case it's middleware that's hijacking the request. (Can't replicate locally)
> GP2-901: Attempt to fix unexpected redirect to Django Admin for Case Study preview

- core/templates/core/page_no_navigation.html
CONTEXT: Hide footer on the root signed-out welcome page.
> Hide footer on the root signed-out welcome page.

- CHANGELOG.md
- core/templates/core/base.html
Suddenly this URL disappeared from base.html. I've readded.
> Added missing population url to base template

- domestic/models.py
This mini changeset cleans up the options when adding a child page to the homepage in Magna - some of the page types available were not relevant.
This is an add-on/defect fix for GP2-1284 so doesn't have a changelog entry.
- [-] Explains how to test locally, including how to set up appropriate data
BEFORE
AFTER
> GP2-1284: Update Wagtail page config to limit what can be a child of the homepage

- CHANGELOG.md
- core/templates/components/header_footer/domestic_header_nav.html
... rather than use BAU-specific URLs from `header_footer_urls`
> GP2-1376: Link Advice and Markets nav items to Magna pages

- CHANGELOG.md
- domestic/templates/domestic/content/country_guide.html
Before it was trying to reverse URL which didn't exist in Django
I know that using `slugurl` isn't much different from using a hard-coded URL, that it still depends on a fixed value _somewhere_ in the system, but Advice is a section we know will 100% exist, and we have to make the link somewhere, so here is at least clearer than using context processors, etc, now that we no longer need to.
> GP2-1368: Wire up link from country_guide.html to /advice/ slug

- CHANGELOG.md
- cms_extras/modeladmin.py
- tests/unit/cms_extra/test_modeladmin.py
This changeset adds related pages to CaseStudy Listing view
> Added related pages to Case Study listing view

- CHANGELOG.md
- domestic/templates/domestic/content/article_listing_page.html
The listing page lacked custom date formatting for articles listed in it.
Before
`Last updated 28 Jan 2021, 2:19 p.m.`
After
`Last updated 28 January 2021`.
> GP2-1408: Fix date formatting of articles on article list page template

- CHANGELOG.md
- core/templates/core/base.html
- core/templates/core/compare_countries.html
- core/templates/core/includes/personalisation_bar.html
On form pages (specifically the upload logo page) the personalization bar was not being populated.
The bar requires the redux store being populated, which in turn required a certain mixin to add the export plan to the page context. The get_context method overridden in the mixin was not called in FormViews, only TemplateViews.
A much simpler (and more reliable) way though is to access the export plan directly from the templates using the request.user context provided by Django on all pages.
> GP2-1360 Personalisation bar on form pages

- CHANGELOG.md
- domestic/migrations/0006_articlelistingpage_articlepage_campaignpage_countryguidepage.py
- domestic/models.py
The field was nullable, but the Wagtail UI wasn't allowing the field to be blank.
Retrospective tweak to original migration done, because blank=True doesn't affect the DB schema (unlike null=True|False)
Before:
After:
> GP2-1411: Allow ArticlePages to have no selected type

- CHANGELOG.md
- domestic/migrations/0008_drop_markdownfield_usage.py
- domestic/models.py
- tests/unit/domestic/test_models.py
This changeset fixes two small things with the Markets page ported from V1:
* **Fix ordering of markets page results** 
Previously, when the markets page was sorted by last updated, it was actually returning pages ordered the least-recently updated because the default ordering of `last_published_at` is ascending not descending.
This fixes that by amending the relevant selected value before it is passed to the ORM.
Note that a better querystring name for date ordering would be clearer, but we need to keep the pattern in use on V1 for now
* **Fix verbose title of field not to mention markdown**
> GP2-1514: Fix markets topic page ordering

- CHANGELOG.md
- domestic/templates/domestic/performance_dashboard_page.html
This one-liner changes the name used for child links displayed on the main/landing Performance Dashboard 
Previously it showed the page's full title
But now it shows the shortened name, which is actually the same of the service it is for
> GP2-1549: Change label shown to child Performance Dashboard

- CHANGELOG.md
- core/constants.py
- domestic/migrations/0016_switch_article_body_text_to_streamfield.py
HOTFIX: reinstate document-link as rich-text field option
Original migration was retrospectively edited, but that is OK because it is not a change that amends the DB-level schema, only software-defined StreamField schema
> HOTFIX: reinstate document-link as rich-text field option

- CHANGELOG.md
- core/utils.py
- tests/unit/core/test_blocks.py
This changeset adds randomness of selecting case study when multiple case study scoring same
> Added logic to pick random case study for same weight

- CHANGELOG.md
- domestic/models.py
- tests/unit/domestic/test_models.py
This changeset makes the inclusion of the two GA360-specific mixins easier
by wrapping them into their own abstract mixin class.
This new `DataLayerMixin` is then added to the `BaseContentPage` for ex-Great-V1 content or
directly into any page that does not use `BaseContentPage`.
There is also a test that checks that all concrete subclasses of wagtail.Page
in domestic.models implement the `DataLayerMixin`. (Opinions welcome about cleaner ways to execute this test.)
eg: without the `DataLayerMixin` included in `BaseContentPage` we get:
```
E           AssertionError: These Domestic pages do not implement the DataLayerMixin, 
but should: [<class 'domestic.models.ArticleListingPage'>, <class 'domestic.models.ArticlePage'>, 
<class 'domestic.models.CampaignPage'>, <class …
```
> GP2-1619: Ensure all pages ported from V1 into Domestic support DataLayer

- CHANGELOG.md
- domestic/migrations/0017_add_guidance_page.py
- domestic/migrations/0018_performancedashboardpage.py
The hotfix to add in the `document-link` option for rich-text blocks worked on master when added to domestic.0016 but migrations on release and develop had moved on (and so the frozen schema no longer reflected the change made to 0016).
This change will remeduy this, but it shows the limitations of editing historical migrations :/
(Editing StreamField schemas is a no-op change at the DB level, so this changeset is 'ok', but it doesn't protect against other edits to the StreamField going on on parallel branches)
Master does not need this fixup, because it doesn't have the extra migrations that staging and develop do, which didn't get the hotfix (because the hotfix targeted master)
> NOTICKET: Add migraition for missing richtext-features change

- CHANGELOG.md
- exportplan/helpers.py
- exportplan/templates/exportplan/sections/target-markets-research.html
- exportplan/views.py
- react-components/src/components/DataSnapShot/ProductData.jsx
- react-components/src/components/DataSnapShot/index.jsx
- tests/conftest.py
- tests/unit/exportplan/test_views.py
PR to implement change to CPI data which have now lost the year-specific field and use ISO2 country codes in requests. 
The export plan market research page data point was broken as the country was requested by name rather than iso2.  This PR fixes that.
> GP2-1441 CPI update

- domestic/models.py
- tests/unit/domestic/test_models.py
Prior to this change, StructuralPage wouldn't allow an ArticlePage to be its child, but would allow various other ones (ie, by default)
This change locks things down so that a) only ArticlePages can be child pages of StructuralPage and b) StructuralPages are allowed to be parents of ArticlePages.
In the future we may want to broaden this out, but for now it meets the criteria for the story
Includes tests
I'll get this into `release` soon too
> GP2-1559: Fixup allowed page types for StructuralPage

- domestic/models.py
- tests/unit/domestic/test_models.py
THIS COMMIT WAS CHERRY PICKED FROM DEVELOP: 4da5a07b741f2d72eb6f76d6f91e401c201e8709
Prior to this change, StructuralPage wouldn't allow an ArticlePage to be its child, but would allow various other ones (ie, by default)
This change locks things down so that a) only ArticlePages can be child pages of StructuralPage and b) StructuralPages are allowed to be parents of ArticlePages.
In the future we may want to broaden this out, but for now it meets the criteria for the story
Includes tests
> GP2-1559: HOTFIX for release branch -- Allowed page types for StructuralPage

- CHANGELOG.md
- core/templates/components/header_footer/domestic_footer.html
- core/templates/components/header_footer/footer_base.html
Updated logged out pages footer to match manga footer links
> GP2-1763 - signed out footer

- CHANGELOG.md
- domestic/templates/domestic/article_listing_page.html
- domestic/templates/domestic/topic_landing_pages/generic.html
Add learning banner on advice listing pages
> Add learning banner on advice listing pages

- CHANGELOG.md
- core/templates/components/header_footer/sso_login.html
Temporarily changes "sign out" to "dashboard" to prevent users being redirected to sso profile sign out
> GP2-1858: Switch sign out to dashboard

- CHANGELOG.md
- search/helpers.py
- tests/unit/search/test_helpers.py
We've been seeing some unexpected/flip-flopping ordering of results on Dev and can't fully explain why the ranking scores for Articles vs Services
This changeset contains a recommendation from @michalc (the creator of DIT's ActivityStream) which moves the boost aspect of the query away from a 'should' clause with potential full-text search matching on the type (which may or may not be conflicting with the un-namespaced Article-type and Service-type records also being ingested from BAU into AS). Instead, we're trying out some clear function-based boosting.
This appears to be better:
1. The scores we're seeing for items returned correspond more predictably to the boosting involved (eg before Services were boosted by 20000, but the score was rarely higher than 13100 for a top-ranked result. …
> GP2-2240: Improve stability of search results ordering/boosting

- CHANGELOG.md
- core/templates/robots.txt
- core/urls.py
- core/views.py
- tests/unit/core/test_views.py
This changeset adds a simple robots.txt file, based on what we used in V1 but extended in line with aspects of great-cms that are pointless for search engines to crawl
* Go to /robots.txt in your local build
> GP2-2156: Add robots.txt to great-cms

- CHANGELOG.md
- config/settings.py
- core/urls.py
- exportplan/core/serializers.py
- healthcheck/apps.py
- healthcheck/backends.py
- requirements.in
- requirements.txt
- requirements_test.txt
- tests/unit/healthcheck/test_backends.py
This changeset brings over /healthcheck/ and /healthcheck/ping/ from V1  to use in Magna
They use the same logic/checks of the required backends (API, Forms, SSO, Search).
The Search backend has been minorly updated to match the updated test data available only on the dev env, so the healthcheck only checks search in dev. This is the same as for V1.
* locally, hit up /healthcheck/?token=debug with and without backing services running locally
Unhappy
Happy
> GP2-2155: Add healthcheck endpoints

- core/templates/components/header_footer/domestic_header_nav.html
- tests/unit/domestic/test_models.py
This changeset fix the account link for the signed-out user
> Bugfix: Account link was appearing for signed out user

- CHANGELOG.md
- core/templates/components/header_footer/footer_base.html
- core/templates/core/footer.html
`/contact-us/help/` is no longer the path we want to send people to - instead they must go to `/contact/` to enter the full BAU contact triage flow 
(`/contact/` will 404 locally, but is the URL path that is custom-routed to the V1 contact pages until they are ported to V2)
There will be related PRs for BAU repos, as this also needs changing in directory-components.
> GP2-2358: Change footer link for contact pages to match custom routing to full contact pages in BAU

- CHANGELOG.md
- learn/templates/learn/automated_list_page.html
> GP2-2507: Remove beta banner from learning

- CHANGELOG.md
- core/templatetags/video_tags.py
- requirements.txt
- requirements_test.txt
- tests/unit/core/test_templatetags.py
* Add preload="metadata" attribute to the video node
* Add #t=0.1 to end of video source URL to allow mobile safari to show a poster-like image
```
<video preload="metadata" controls="" poster="https://media.example.com/media_thumbnails/one-minute-video_gs7fCNL.png" data-v-duration="60">
<source src="https://media.example.com/media/one-minute-timer_GbCdImp.mp4#t=0.1" transcript="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Utrum igitur tibi litteram videor an totas paginas commovere? Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. Duo Reges: constructio interrete." type="video/mp4">
Your browser does not support the video tag.
</video>
```
> GP2-2415: Amendments to video component

- CHANGELOG.md
- domestic/templates/domestic/domestic_dashboard.html
The dahboard layout does not look good on tablet screen sizes. This PR makes the dashboard 2 -> 1 column breakpoint occur at 1024 pixels
> GP2-2512 - Dashboard - one column on tablet

- CHANGELOG.md
- core/urls.py
- core/views.py
- tests/unit/core/test_views.py
CONTEXT: This changeset adds a new view for brokering a sign out request from a logged-in BAU user.
> Add sign out view

- CHANGELOG.md
- config/settings.py
- domestic/models.py
- tests/unit/core/test_views.py
This tidies some of the alerts in PROD. Events are currently used on the platform including user location. After confirming with Suraj it was advised to remove these features all together.
> GP2-2868-Tidy-sentry-alerts

- CHANGELOG.md
- core/templates/core/header.html
Re-arrange the chunks on the magna header so the tab order is logical.
Note, the menu and dashboard link are absolute so the DOM position doesn't affect the physical position.
> GP2-2884 - DAC Focus Order 01

- CHANGELOG.md
- search/urls.py
CONTEXT: This changeset updates the search URL so that the search view skips the GA360 mixin
> Skip GA360 on search path

- requirements.in
- requirements.txt
- requirements_test.txt
> GP2-2981: Update directory-forms-api-client requirement to stop blow-up

- CHANGELOG.md
- core/urls.py
- core/views.py
- core/views_api.py
- domestic/static/javascript/company-lookup.js
- tests/unit/core/test_views.py
There were two api views in the system.  One called by JavaScript in a migrated BAU form. The other used                                                    within Magna for VFM.
This PR, switches the BAU javascript to use the same api view as Maga react code, and removed the surplus api view along with tests.
> GP2-2986 Merge companies-house api views

- CHANGELOG.md
- contact/forms.py
- tests/unit/contact/test_forms.py
BUGFIX: Make the name fields in the SOO contact wizard to still be editable if the first and/or last name is not yet known
This is needed because Great V2 allows users to sign up without providing a first or last name, which would then cause the overall wizard to 500.
**NOTE THAT this fix is being applied to the pages after they have been migrated from V1 into V2, but if we decide we want to hotfix this to production on GDUI, it is a copy-paste change to port over.**
Tests work at the Python level, but tested manually, too, of course.
**BEFORE** - see https://uktrade.atlassian.net/wiki/spaces/Great/pages/2681405487/SOO+applications+-+make+first+and+last+name+fields+editable
**AFTER**
- Leave to Steve to merge into a different target branch, after GP2-1648 has been merged to the …
> GP2-2988: Fix SOO contact form - make empty name fields editable

- CHANGELOG.md
- config/settings.py
- contact/forms.py
- contact/templates/domestic/contact/soo/base.html
- contact/templates/domestic/contact/soo/step-applicant-details.html
- contact/templates/domestic/contact/soo/step-applicant.html
- contact/templates/domestic/contact/soo/step-contact-details.html
- contact/templates/domestic/contact/soo/step-experience.html
- contact/urls.py
- contact/views.py
- sso/models.py
- templates/great_components/form_widgets/README.txt
- templates/great_components/form_widgets/form.html
- templates/great_components/form_widgets/form_field.html
- templates/great_components/form_widgets/multiple_input.html
- templates/great_components/form_widgets/nested-radio.html
- templates/great_components/form_widgets/radio_option.html
- tests/unit/contact/test_forms.py
- tests/unit/contact/test_views.py
- tests/unit/sso/test_models.py
This changeset ports the pages at /contact/selling-online-overseas/* from V1 into V2.
These pages, which require a user to be signed in, are how someoene applies for support.
Note that the workflow expects a ?market=Name%20Of%20Company querystring, else will show None in the breadcrumbs and have only a partial headline if you just go directly to /contact/selling-online-overseas/ -- this is expected/current behaviour
Also note that if you have a user account created purely in Magna, it will lack a first and last name, which will stop you completing the wizard. That bug will be handled in a separate PR, as it's an existing issue.
**IMPORTANT**
This changeset also required extra work to port/fix broken styling in these SOO contact pages.
The root cause of this was basically:
* great-cms uses …
> GP2-1684: migrate SOO contact pages

- core/cms_slugs.py
- core/forms.py
- tests/unit/core/test_form.py
This changeset fixes a slip where we were linking to the regular privacy policy from the contact-consent partial, instead of a special document/page that specifically dealt with the contact pages.
> GP2-1688: Fix link to specific privacy page in contact-consent panel in contact forms

- CHANGELOG.md
- exportplan/templates/exportplan/section.html
Adding XL margin to top of the purple container that comes after forms. Ticket mentions 100px; using this spacing token means 90px but consistency with design system.
> GP2-2491 Add spacing at end of forms

- domestic/gulpfile.js
- domestic/package-lock.json
- domestic/package.json
Update `gulp-sass` to remove high severity vulnerabilities.
> GP2-3164 Update vulnerable domestic dependencies

- CHANGELOG.md
- core/urls.py
CONTEXT: This changeset emoves GA tracking on `/signup`
> [GP-3282] Backport to develop: skip GA on signup

- CHANGELOG.md
- exportplan/templates/exportplan/pdf_download.html
Amends GBP under Total funding
SS Before:
After:
> GP2-3384 Amends GBP per unit to GBP in PDF under total funding.

- CHANGELOG.md
- sso/views.py
- tests/unit/sso/test_views.py
Suppress error message when signing up a user whose email is already registered.
> [GP2-3406] Suppress error when user is already registered

- requirements.in
- requirements.txt
- requirements_test.txt
Our elasticsearch instance won't work with client versions later than 7.13.4
This pins at 7.9.1 - a known working version
> GP2-3192 downgrade es client

- core/components/package-lock.json
- domestic/package-lock.json
- domestic/package.json
Updates to ansi-regex in domestic and core/components
> Gp2 3684 vulns

- CHANGELOG.md
- exportplan/templates/exportplan/includes/sidebar.html
Prevent the glitch on loading export plan caused by the sidebar being expanded in the initial template render.
> GP2-3822 - Export plan - fix sidebar flicker

- CHANGELOG.md
- core/utils.py
- tests/unit/core/test_utils.py
When a wagtail logged in user saves a lesson. get_personalised_choices method falls over since no sso user is present. I've assumed this is because a page load is triggered during lesson save causing case studies to load with personalised content.
> GP2-3844-hotfix-savingcms-pages

- CHANGELOG.md
- core/templatetags/to_json.py
- exportplan/templates/exportplan/includes/pdf/pdf_section_adapting_your_product.html
- exportplan/templates/exportplan/includes/pdf/pdf_section_business_objectives.html
- exportplan/templates/exportplan/includes/pdf/pdf_section_funding_and_credit.html
- exportplan/templates/exportplan/includes/section_data/travel-and-business-policies__data.html
- exportplan/templates/exportplan/pdf_download.html
- exportplan/templates/exportplan/section.html
- exportplan/templates/exportplan/sections/adapting-your-product.html
- exportplan/templates/exportplan/sections/business-objectives.html
- exportplan/templates/exportplan/sections/business-risk.html
- exportplan/templates/exportplan/sections/funding-and-credit.html
- exportplan/templates/exportplan/sections/getting-paid.html
- exportplan/templates/exportplan/sections/marketing-approach.html
- exportplan/templates/exportplan/sections/target-markets-research.html
All the export plan text fields seem to translate an apostrophe to html encoding.
It seems the culprit is the to_json template tag which does a replace of apostrophes with malice aforethought.
As I originally checked that tag in and I've no idea why I put the translation in, seems safe to get rid!
This PR also has a bit of tidying - removing to_json from templates where it's not used and removing the '|safe' filter as to_json already returns a safestring.
> GP2-3846 - Remove html encoding from apostrophes in to_json tag

- CHANGELOG.md
- exportplan/context.py
Another PR on this ticket added ordering of business objectives and trips to the FE so that the lists are always displayed and saved in the right order.
This however doesn't fix the export plan for existing export plans which may be wrongly ordered. This PR fixes that.
> GP2-3834 PDF: Force order of existing export plan business trips 

- CHANGELOG.md
- exportplan/templates/exportplan/sections/business-objectives.html
- exportplan/templates/exportplan/sections/costs-and-pricing.html
- exportplan/templates/exportplan/sections/funding-and-credit.html
- exportplan/templates/exportplan/sections/getting-paid.html
- exportplan/templates/exportplan/sections/marketing-approach.html
Adds a json filter to the rendering of lesson blocks inside script tags on payments page of EP.
The actual instance causing the issue had no filter (I think it was my bad) but I've changed others to use |to_json rather than |safe
We should always use |to_json really as it will correctly render booleans and None values in json rather then the python to-string.
> GP2-3858 - Fix export plan payment terms

- CHANGELOG.md
- domestic/management/commands/organise_country_guide_ctas.py
- domestic/models.py
- domestic/templates/domestic/country_guide.html
- tests/unit/domestic/management/commands/test_organise_country_guide_ctas.py
- tests/unit/domestic/test_models.py
Requires #1745 
Adds the Trade barriers and Duties and customs procedures content underneath the accordion. Updates the 'Next steps' cards to show both Trade barriers and Duties and customs links.
> Gls 112 trade barriers

- CHANGELOG.md
- domestic/management/commands/update_factsheets_cta_links.py
- tests/unit/domestic/management/commands/test_update_factsheets_cta_links.py
Adds a command to automatically update factsheets links based on data from the govuk content API:
```
make manage update_factsheets_cta_links
```
Similar to the `organise_country_guide_ctas` command, a `--dry_run` option can be passed to simulate the update without updating actual data.
> GLS-113 Add command to update all factsheets links from govuk content API

- CHANGELOG.md
- GLS-113 - add extra items and heading to Country Guide CTA links
- GLS-113 - add command to update factsheets links from govuk content API
- GLS-112 - add Trade barriers and Duties and customs content
> Post release changelog update - 2.5.0

- package-lock.json
- package.json
Prevents an issue in IDE where `eslint` fails to run due to a misconfiguration in the AirBnb plugin.
> Pin eslint version to prevent misconfig

- CHANGELOG.md
Note: for some reason the sign-up page styling updates had been added to the previous release -- this was incorrect, so has been rectified here.
> Update changelog - v2.6.0

- core/templates/core/includes/data_source.html
- domestic/models.py
- domestic/templates/domestic/country_guide.html
Some more tweaks and updates to the country guide page:
- Tweak bar charts so label is always shown fully (font-size decreased, adjusted spacing to fit more text)
- Update 'Data Source' template to include:
- Next release
- Notes
- Updated data hardcoded for China (this updates the metadata schema slightly!)
> GLS-180 visualisation tweaks

- CHANGELOG.md
- domestic/templates/domestic/country_guide.html
Add `id` attributes to tab buttons so GTM tracking per tab can be isolated more effectively.
> GLS-210 Add id attributes to tabs for improved tracking

- CHANGELOG.md
No idea how the entry for GLS-186 had ended up under 2.7.0, and why some
of the tickets were missing... /shrug
> Post release changelog update - 2.9.0

- package.json
`npm run build-domestic:dev` was failing due to the project root not being included in the sass load path.
> Add project root as load path for build-domestic:dev target

- CHANGELOG.md
- config/settings.py
- package-lock.json
Added filetype restriction for wagtail documents to be uploaded.
> Added restriction of uploading document by file types

- CHANGELOG.md
- core/admin.py
Disable autocomplete for user creation and password reset forms, as per the pen test recommendations.
> Disable autocomplete for user creation and password reset forms

- CHANGELOG.md
- core/validators.py
- tests/unit/core/test_validators.py
CONTEXT: The logo file uploaded through the business profile form is instantiated as an `InMemoryUploadedFile`, which is read by the file infection validator and sent over to the Clam AV service for scanning. In this process the file object loses the current position and does not get stored.
This hotfix resets the current position of the file so it can be read and stored after being scan-validated.
> [HOTFIX] logo not uploading to business profile

- CHANGELOG.md
- core/validators.py
- tests/unit/core/test_validators.py
CONTEXT: The logo file uploaded through the business profile form is instantiated as an `InMemoryUploadedFile`, which is read by the file infection validator and sent over to the Clam AV service for scanning. In this process the file object loses the current position and does not get stored.
This hotfix resets the current position of the file so it can be read and stored after being scan-validated.
> Backport to Release: [HOTFIX] logo not uploading to business profile

- CHANGELOG.md
- core/validators.py
- tests/unit/core/test_validators.py
CONTEXT: The logo file uploaded through the business profile form is instantiated as an `InMemoryUploadedFile`, which is read by the file infection validator and sent over to the Clam AV service for scanning. In this process the file object loses the current position and does not get stored.
This hotfix resets the current position of the file so it can be read and stored after being scan-validated.
> Backport to Develop: [HOTFIX] logo not uploading to business profile

- CHANGELOG.md
- core/templates/robots.txt
- pii-secret-exclude.txt
- tests/unit/core/test_views.py
This PR removes the `/admin` and `/django-admin` paths from the robots.txt file.
This is based on advice from our pen test, as these routes are behind our IP filter anyway, so are not accessible by robots anyway. 
Because `/api` and `/activity-stream` are only accessible via API key and not through a browser, we are okay to leave these in.
> Remove admin paths from robots disallowed list

- CHANGELOG.md
- sso/views.py
This change corrects an issue where url parameters were being passed as tuples and were therefore creating incorrect urls.
> Fix incorrect next url being sent when exired verification is entered

- CHANGELOG.md
- core/templates/core/header.html
- domestic/templates/domestic/base.html
This PR addresses the duplication of meta tags and rendering of empty meta tags in pages which extend from `domestic/base.html`. This is done by:
- Removing the inclusion of `wagtailseo/meta.html` in the base template, as it's already included in `header.html` which is used in the base template.
- Only including `wagtailseo/meta.html` in Wagtail pages, because if the page doesn't use wagtail all meta/title tags will be empty, as they are taken from the Wagtail `page` object ([see docs](https://docs.coderedcorp.com/wagtail-seo/getting-started/edit-meta.html#specifying-metadata-per-page)).
**To test**:
- Pull branch, and visit http://greatcms.trade.great:8020/get-finance/
- Inspect the html, there should only be one of each of these tags `<title>, <meta name="title"> and <meta …
> Remove duplicate and empty meta tags from domestic templates

- CHANGELOG.md
- domestic/templates/domestic/includes/article_detail_content.html
This PR fixes a bug in which the 'Tell me more banner' appears on all types of article page.
The banner should now only appear on advice article pages.
**Test locally:**
- After pulling branch go to `campaigns/local-export-support/` - there should be no 'Tell me more banner' at the bottom of this page
- Go to `/advice/create-export-plan/how-create-export-plan/` - you should see the 'Tell me more banner' at the bottom of the page
**Screenshot - advice page**
**Screenshot - campaign page**
> Only show Want to know more banner on advice pages

- CHANGELOG.md
- core/helpers.py
- domestic/models.py
- tests/unit/core/test_helpers.py
- tests/unit/domestic/test_models.py
This PR makes a fix to the logic around getting statistics for the country guide page.
Currently all stats are fetched from the API only when the feature flag `FEATURE_SHOW_MARKET_GUIDE_VISUALISATIONS` is enabled. However, the GDP per capita and economic growth stats should always show - regardless of whether the flag is set to true or false. This PR updates this logic so that these stats always show.
Once the flag is turned on permanently, the additional helper function I have added will be removed.
**To test**
1.  Set `FEATURE_SHOW_MARKET_GUIDE_VISUALISATIONS` to false in `secrets-do-not-commit`
2. Go to http://greatcms.trade.great:8020/markets/fiji/
3. You should still see the GDP per capita and Economic growth stats in the 'At a glance panel'
> Always show economic highlights stats - not dependent on feature flag

- core/constants.py
- core/templates/components/statistics_card_grid.html
- core/templates/core/includes/bar_chart.html
- core/templates/core/includes/data_source.html
- domestic/management/commands/update_factsheets_cta_links.py
- domestic/models.py
- domestic/templates/domestic/country_guide.html
- domestic/templates/domestic/includes/market_guide_graph_data_source.html
- tests/unit/domestic/test_models.py
This PR updates the market guide pages to:
- Pull in data on the source of our statistics from the API
- Display the source data on the trade highlights statistics and three graphs
- Have a property `country_fact_sheet_link` in order for this to be downloadable for each country
- Have more consistent styling
To test locally:
- Switch `FEATURE_SHOW_MARKET_GUIDE_VISUALISATIONS` to True
- Go to http://greatcms.trade.great:8020/markets/china/
**Screenshots - BEFORE**
**Screenshots - AFTER**
> Add source information to market guides

- contact/views.py
- core/templates/core/includes/contact-consent.html
- tests/unit/contact/test_views.py
This PR fixes an issue introduced by #1914 where the `privacy_url` variable is not passed to the FTA form, meaning that currently the privacy notice link at the bottom of the form page just links to the current URL.
**Before**
**After**
> Pass privacy policy url to FTA form template

- CHANGELOG.md
- contact/templates/domestic/contact/includes/office-contact-cta.html
- contact/templates/domestic/contact/office-finder.html
This PR fixes an error in which the wrong destinations were applied to the Scottish enterprise and DIT Scotland office's contact buttons.
Since both offices need to have a region of `scotland` in directory API to be matched with Scottish postcodes, the logic now checks the name of the office, and if it is the Scottish Enterprise office, uses their website URL as the destination of the contact button.
The styling of the Scottish Enterprise contact us link has also been made consistent with all other offices - showing a button rather than a link. Shown below.
**TODO**
If more offices ask to be contacted via their website rather than our contact form, we should add a field to the [trade office model in directory-api](https://github.com/uktrade/directory-api/blob/develop/exporting/models.py#L6 …
> Correct contact CTA destinations for Scottish trade offices

- CHANGELOG.md
- sso/views.py
Updated login error message from  “Incorrect username or password” to "Incorrect email address or password" to make it clearer that a user needs to enter a valid email on sign in.
Before:
After:
To test locally go to http://greatcms.trade.great:8020/login/  and attempt to login with a non-existent user.
> Update error message for "Incorrect username"

- CHANGELOG.md
- core/urls.py
- core/views_api.py
- requirements.in
- requirements.txt
- requirements_test.txt
- tests/conftest.py
- tests/unit/core/test_views.py
This PR adds a view which, given a survey id, fetches a survey's details from directory API via the API client.
This is the first piece of work towards creating a new survey for potential exporters on the site.
**To test**
- Add a survey to your local directory API instance, copy the ID of the survey
- In your browser go to `http://greatcms.trade.great:8020/api/survey/<ID>`
> KLS-266 - Get survey details from directory API

- CHANGELOG.md
- export_academy/templates/export_academy/event_list.html
Add duration of webinar to event listing page.
> KLS 270 - add webinar duration to listing page

- CHANGELOG.md
- export_academy/views.py
- export_academy/wagtail_hooks.py
- tests/unit/export_academy/test_wagtail_hooks.py
CONTEXT: This changeset brings the ability to clone events from Wagtail admin.
> Clone events on Wagtail admin

- export_academy/helpers.py
- tests/unit/export_academy/test_helpers.py
This PR ensures that the 'Book' button is shown for users who are not logged into export academy and additionally displays the 'Join' button upon booking.
> Eam 104 refine

- CHANGELOG.md
- config/urls.py
- international_online_offer/templates/ioo/index.html
- international_online_offer/views.py
The service name has now been agreed and is "Expand your business in the UK". Change to the headings referencing this and the main entry point url for the service.
> Ioo 443 service name change

- core/templates/components/card.html
- tests/unit/domestic/test_models.py
This PR links the "Sign in required" buttons on the great dashboard to the login page. To test go to the logged out dashboard and try the "Sign up required" buttons
> Link "Sign in required" button to login page

- domestic/static/javascript/eventFilters.js
- export_academy/templates/export_academy/event_list.html
This PR adds javascript logic which will scroll the user to the top of the list of results (ie the breadcrumbs component being at the top of the screen) when a user selects a filter.
This scrolling behaviour will occur when:
- There are query parameters are in the url (which happens when filters are applied)
- The referrer url contains `/events/` (to prevent the scrolling happening on book marked or shared links)
**To test**
- Go to `export-academy/events/`
- Select a filter
- When the page reloads, the breadcrumbs element should be at the top of your screen
> KLS-540 - Scroll to top of results when EA filters are refreshed

- config/settings.py
This PR updates the type of the breadcrumb URL environment variable to a string so the URL can be used in code.
> Update breadcrumbs env. type

- export_academy/templates/export_academy/includes/event_name_duration.html
This PR is a hotfix for a bug on the event listing page which causes the page to break if the user is logged out.
The change only calls `user_is_booked_on_event` if the user is not anonymous.
> Hotfix - add logic to only get booking data if user logged in

- core/templates/robots.txt
- tests/unit/core/test_views.py
We are being crawled and attacked via a bot called MJ12bot. Its slowing the international website. Putting this robots.txt fix in to disallow access
> Disallow bot access via robots

- export_academy/models.py
- export_academy/templates/export_academy/booking_success.html
- export_academy/urls.py
- export_academy/views.py
- tests/unit/export_academy/test_models.py
- tests/unit/export_academy/test_views.py
This PR adds the frontend for the registration success page. It also updates the registration and cancellation success URLs to be clearer.
These are now:
- Registration: `registration/booking/<uuid:booking_id>/success/`
- Cancellation: `booking/<uuid:booking_id>/cancellation/success`
**Screenshot Desktop**
**Screenshot mobile**
**To test**
- Make sure you've removed your local registration instance
- Go to `/export-academy/events` and click book on an event
- Go through the registration form
- At the end you should see the confirmation page
> Add event registration confirmation page

- export_academy/helpers.py
- export_academy/mixins.py
- export_academy/urls.py
- export_academy/views.py
- tests/unit/export_academy/test_views.py
This PR makes two fixes to the export academy registration flow:
1) Updates the URL parameter representing an event id to be `event_id` rather than `booking_id`
2) Updates the query to get the user's `booking_id` in the redirection to the registration success page to ensure it gets the booking object related to the current user
> Event registration naming & booking query fixes

- core/static/javascript/international-online-offer.js
UR showed that users searching for food & beverage and beverage weren't able to select food and drink as a parent category. Adding in additional tags to enable this.
> Add search words beverage to food drink parent

- core/templates/robots.txt
- tests/unit/core/test_views.py
Hotfix PR to block crawling from two particular bots via our robots.txt file.
> HOTFIX - Disallow crawling from specified bots in robots.txt

- core/templates/robots.txt
- tests/unit/core/test_views.py
This PR backports a hotfix which was applied to the master branch - see PR here #2206 .
> Backport hotfix - Disallow crawling from specified bot in robots.txt

- config/settings.py
- core/helpers.py
- requirements.in
- requirements.txt
- requirements_test.txt
This PR fixes an issue which, since upgrading to django 4.1.9, meant that we had lost auto-reloading after changing an html template. The issue was caused by the `runserver_plus` command coming from `django-extensions` package, and fixed in version 3.2.3.
The newer version now calls the `django.template.autoreload.get_template_directories` method, which in turn calls [django.utils._os.to_path](https://github.com/django/django/blob/main/django/utils/_os.py#L56). This method relies on paths being either in string format or an instance of `pathlib.Path`. Because we create our `ROOT_DIR` path in settings.py using `environ.path` - this was causing `get_template_directories()` to give an error.
So this PR also updates our directory paths in settings.py to use `pathlib.Path`. This now looks to …
> Fix template auto-reloading

- activitystream/serializers.py
- activitystream/urls.py
- activitystream/views.py
- pii-secret-exclude.txt
- tests/unit/activitystream/test_serializers.py
- tests/unit/activitystream/test_views.py
CONTEXT: This changeset adds an endpoint for Activity Stream to consume UKEA's registrations.
> Activity Stream endpoint for UKEA's registrations

- core/wagtail_hooks.py
Ticket: https://uktrade.atlassian.net/jira/software/projects/KLS/boards/359?assignee=63343adf88ed2ebef97c64ac&selectedIssue=KLS-768
Migrated page at bottom
settings use domestic logo is now ticket by default after migrating to microsute page
> Set use domestic header to true for article pages converted to microsites

- contact/forms.py
- contact/templates/domestic/contact/export-support/step-2.html
- contact/templates/domestic/contact/export-support/step-4.html
- contact/templates/domestic/contact/export-support/step-5.html
- contact/urls.py
- contact/views.py
- tests/unit/contact/test_forms.py
- tests/unit/contact/test_views.py
Adds the fourth form the new "Digital point of Entry" contact support form.
To test locally go to "http://greatcms.trade.great:8020/contact/domestic/export-support/"
Fill in the first, second and third steps of form and then click "Continue" button. You will be redirected to the fourth step.
On successful submit the form redirects to an empty page where the fifth step form will be located in a future ticket.
> DPE-163: fourth step

- config/settings.py
- config/utils.py
- requirements_test.txt
- tests/unit/config/test_utils.py
This PR updates the configuration of wagtail transfer to include our new page models, resolve circular dependancies on page modals and prevent the duplicate key error on username. I have also expanded the list of environments from which staging can pull in pages. It should now be possible for the content designer to move and view a page in any environment.
To test locally:
- set WAGTAIL_TRANSFER_LOCAL_DEV to true in secrets-do-not-commit
- create a new database called greatcms_transfer_target
- with this new database referenced in secrets-do-not-commit run migrations
- update the make webserver command to use port 8030 and spin it up
- revert the previous to changes and spin up greatcms on port 8020
You should now have two instances running locally that you can use wagtail transfer …
> Wagtail transfer configuration updated

- core/templates/microsites/blocks/columns.html
- core/templates/microsites/blocks/cta.html
- core/templates/microsites/blocks/streamfield.html
This PR is to fix a bug that was introduced when deploying tickets KLS-765 and KLS-730. The tickets enabled the persistence of language across microsite's and to alter the CTA teaser field to provide richtext. 
fixes:
Language persistence: I have changed how blocks are included in the streamfield.html template. We now use Wagtails include_block template tag as it passes the request to the block templates. Therefore we can use the persist_language filter without error.
CTA: I have added the richtext tag to render the html correctly.
> added include_block to pass request and richtext filter to cta teaser

- export_academy/templatetags/event_list_buttons.py
This PR fixes a bug where in `_get_display_name_for_filters` it tries to find the display name from the filter form for all filters applied (apart from booking_period). Because the page filter doesn't come from the filter form, it throws a key error for the page filter when it looks for it in the form fields.
> HOTFIX - don't get display name for filter if page filter

- export_academy/templatetags/event_list_buttons.py
Backports a hotfix commit made on master. See PR #2260
> Hotfix backport - don't get display name for filter if page filter

- export_academy/templatetags/event_list_buttons.py
- tests/unit/export_academy/test_views.py
This PR refactors the way display names for applied filters are computed. It now loops over the fields from the filter form, rather than the query parameters, so as to avoid including any non-filter parameters such as `page` or `next`.
It also adds a test for pagination on the events list page which would catch issues such as #2261 in the future.
**To test**
- Go to /export-academy/events
- Select filters down the left (not including booking period) and click apply filter
- These should appear in a summary 
- Assuming you have more than 10 events locally, going to `?page=2` should successfully render the second page of results
> Refactor filter summary and improve tests

- contact/templates/domestic/contact/includes/office-contact-cta.html
This ticket adds a region office divert for East and West Midlands to the Contact Us form. 
TO TEST: Simply search for a postcode for both East and West Midlands int he /contact-us/office-finder section of great-cms. Ensure the the link for the region office goes to: https://www.gov.uk/ask-export-support-team
- [X ] Ticket exists in Jira https://uktrade.atlassian.net/browse/KLS-724
- [X ] Explains how to test locally, including how to set up appropriate data
> Kls 759 change contact form settings for west midlands and east midlands office finder

- international_online_offer/forms.py
- international_online_offer/templates/ioo/edit_your_answers.html
- international_online_offer/templates/ioo/guide.html
- international_online_offer/templates/ioo/triage/intent.html
- international_online_offer/views.py
- tests/unit/international_online_offer/test_views.py
We had a bug where users triage session data was being lost when signing up. Although this should only happen if the session cookie is wiped there is now a fix in place which force saves the session data on signup and deletes the session data as its no longer required.
> Fix to help save triage data when user signs up

- export_academy/helpers.py
- export_academy/mixins.py
- export_academy/templates/export_academy/accounts/includes/existing_user_body_text.html
- export_academy/templates/export_academy/accounts/signin.html
- export_academy/views.py
- tests/unit/export_academy/test_helpers.py
- tests/unit/export_academy/test_views.py
This PR updates the sign in and sign up flows for users already registered to the Export Academy to fetch the user's registration object (and pre-populate their email address in the template) using a combination of `idb64` and `token` query parameters.
The idb64 value represents a user's aventri registration id, base 64 encoded.
The token represents a hashed version of the same user's email address.
To get the correct registration object:
- the aventri id (ie `Registration.external_id`) is decoded
- the user with that external_id is found
- the email address related to that registration object is hashed
- this hashed email is compared to the token in the query params
- if these values match, the user's email address is pe-populated in the sign in/up form
**To test locally**
- make sure …
> Resolve EA user registration from unique link for sign up/in

- export_academy/templates/export_academy/accounts/includes/existing_user_body_text.html
- export_academy/templates/export_academy/accounts/includes/new_user_body_text.html
This PR makes sure that the link text on the sign in and sign up pages for export academy are font 24.
To test
- Go to http://greatcms.trade.great:8020/export-academy/signup
> Fix font size of signup/in link text

- export_academy/templatetags/event_list_buttons.py
This PR puts the booking period filter on the events list page behind the export academy release 2 feature flag.
**To test**
- Log in locally
- go to /export-academy/events
- The booking period filter (all, current bookings, past bookings) should not be visible
> KLS-859 - Put event booking period filter behind feature flag

- core/wagtail_hooks.py
- tests/unit/core/test_wagtail_hooks.py
Adds a wagtail hook that checks whether the draftail-toolbar is null, and if it is, sets it's value to sticky.
To test: Load up any page in wagtail that has a rich text field after clearing your browsing data, check that the toolbar is pinned.
> Set draftail toolbar to sticky by default

- export_academy/helpers.py
- tests/unit/export_academy/test_views.py
This PR updates the `check_registration` method to redirect to the export academy sign up page when a logged-out user clicks the 'Book' button on an event. Rather than redirecting to the standard Great sign up page.
**To test**
- When logged out, go to http://greatcms.trade.great:8020/export-academy/events/
- Click the 'Book' button on an event
- You should be redirected to http://greatcms.trade.great:8020/export-academy/signup
> Redirect to EA signup from book button

- .circleci/config.yml
- config/settings.py
- pii-secret-exclude.txt
- pytest.ini
- tests/__init__.py
- tests/test_settings.py
- tests/unit/sso/test_backends.py
- tests/unit/sso_profile/enrolment/test_views.py
This PR updates the session engine to use redis cache as its backend, rather than the current signed_cookies backend. This will fix an issue where wagtail page previews (the data for which is stored in django's session) break due to the size of the session cookie being too large.
To avoid having to mock redis for every test that accesses the session (180), this PR also sets the default database session backend to be used by tests.
This change will not affect user's logged in sessions as this is handled by a separate cookie - not django's session cookie.
**To test locally**
- Log into wagtail locally
- You should see a `sessionid` cookie in your browser whose key will match a key in your local redis instance.
> Update session backend to use redis cache

- export_academy/templates/export_academy/accounts/signin.html
- export_academy/templates/export_academy/accounts/signup.html
This PR adds additional help text to the export academy sign in and sign up forms, so that users can still see the options to sign in if on the signup page and vice-versa on all screen sizes.
This text will not be visible when migrated users access this page via a unique link.
**To test**
- Go to /export-academy/signup or /export-academy/signin
**Sign up page**
**Sign in page**
> KLS-931 Add additional text to export academy signin/signup forms

- international_online_offer/core/choices.py
Fixes bug in EYB whereby once a user selects "East" as a sector validation was failing.
> IOO-673: East location validation error

- core/templates/core/get_export_help_experiment_confirmation.html
- core/templates/core/get_export_help_experiment_results.html
- domestic/templates/domestic/includes/experiment-landing-page-hero.html
This PR makes three small fixes to the get export help experiment feature:
- Adds a question mark at the end of the landing page hero heading
- Corrects the container class used on the confirmation page to make it 75% width
- Makes the feedback link on the results page open in a new tab
> Minor fixes for get export help experiment pages

- international_online_offer/core/helpers.py
- international_online_offer/models.py
- international_online_offer/templates/eyb/article.html
- tests/unit/international_online_offer/test_helpers.py
Content want the salary and rent components to show on article pages that have been tagged with the relevant tag. 
N/A
> Showing rent or salary component on tagged pages

- package-lock.json
- package.json
Added an override is package json so installed dependancy will be at least 4.1.3 which is the patched version
https://uktrade.atlassian.net/jira/software/projects/KLS/boards/359?assignee=63343adf88ed2ebef97c64ac&isInsightsOpen=true&selectedIssue=KLS-999
> Bump tough cookie to least 4.1.3 as a dependancy

- export_academy/models.py
This PR is to apply a simple fix to stop emails from being sent to users that have booked onto an event and subsequently cancelled. Prior to this change, reminder and follow-up emails were sent regardless of booking status.
> Change booking query to exclude any with status 'Cancelled'

- international_online_offer/core/helpers.py
- international_online_offer/forms.py
- international_online_offer/models.py
- international_online_offer/templates/eyb/guide.html
- tests/unit/international_online_offer/test_helpers.py
- tests/unit/international_online_offer/test_views.py
Check that user has completed triage on guide and message asking them to complete it. This comes as a change as we've noticed users that signup before going through the triage are coming through to the dashboard and we need this additional IST need this information to help guide them down the line.
The idea was to remove sign in link but this breaks the returning user journey 
The second idea was to change the signup success message to show signed up but not completed triage. These are separate flows and should be considered this way, plus we also need to show the message of triage incomplete if a user has got to the guide page, is logged out and has not yet signed up.
Solution was instead to show this message any time the triage is incomplete.
N/A
> Check that user has completed triage on guide

- export_academy/cms_panels.py
- export_academy/templates/wagtailadmin/export_academy/panels/bookings_inline_panel.html
- export_academy/templates/wagtailadmin/export_academy/panels/bookings_inline_panel_child.html
CONTEXT: This PR brings back the attendance tab to the event's edit page in Wagtail Admin.
> Reinstate the event's attendance tab in Wagtail Admin

- export_academy/templates/export_academy/landing_page.html
This PR updates the logic in the export academy landing page hero so that the logged in content appears when a user is logged in, not just when they're registered with EA.
To test
- Delete your local registration instance if you already have one - `make manage shell_plus` + `Registration.objects.get(email='<your-email>').delete()`
- Go to http://greatcms.trade.great:8020/export-academy/
- When signed OUT you should see the sign up button and text, when signed in you should see the 'View all events' button
> KLS-1079 - Update logic for content on EA landing page hero

- export_academy/cms_panels.py
Editing an event with > c. 330 attendees causes a 400 error because the maximum number of form fields is sent. This change disables the attendance tab temporarily so that events can be modified.
1. Visit the events page in Wagtail admin
2. Click edit on an event
3. The 'Attendance' tab should not be displayed
> KLS-1142 - disable attendance tab on wagtail events

- config/settings.py
- requirements.in
- requirements.txt
- requirements_test.txt
This feature enables content designers to use the anchor-link feature of wagtail. Wagtail does not provide a way to create a target of the anchor link to reference on same page. This change will allow the target be created within a RichText Field.
1. Removes duplicate wagtail link creation icons
2. Ensures anchor links are persisted
3. Support multiple anchor-links
> KLS-1126 fix issue with disappearing anchor links and persist links

- domestic/templates/domestic/landing_page.html
- tests/unit/domestic/test_models.py
Fixes this issue for updated homepage cards:
> DPE-458: fix broken card layout

- core/templates/components/informative_banner.html
- domestic/templates/domestic/landing_page.html
- domestic/templates/domestic/marketaccess/report_a_barrier.html
This PR updates the content relating to reporting a trade barrier on the homepage and at `/report-trade-barrier`.
**Homepage**
**Report a trade barrier page**
> Update 'report a trade barrier' content

- domestic/templates/domestic/base.html
- export_academy/templates/export_academy/event_details.html
This PR removes the breadcrumb block from domestic/base.html and updates the template for the events details page so that the breadcrumbs still show. This resolves the duplicate breadcrumbs elsewhere on the site.
To test check the links in the footers (i.e. terms and conditions) and there should no longer be double breadcrumbs. additionally check the event details page, the breadcrumbs should still be visible.
> Remove breadcrumb block causing duplicate

- domestic/templates/domestic/base.html
- export_academy/templates/export_academy/event_details.html
This PR moves breadcrumbs back out of the content block on the EA details page. This allows the skip to main content link to bypass the breadcrumbs to improve accessibility.
> Reintroduce accessibility change to breadcrumbs

- config/settings.py
- core/middleware.py
- pii-secret-exclude.txt
- requirements.in
- requirements.txt
- requirements_test.txt
- tests/unit/core/test_middleware.py
CONTEXT: This changeset brings missing application security headers into the global responses as per list:
- `Content-Security-Policy` via the [django-csp](https://github.com/mozilla/django-csp) library
- `X-Permitted-Cross-Domain-Policies` via a custom middleware class
> Add middleware to limit data on the domain and CSP via HTTP headers

- domestic/templates/domestic/cookie-preferences.html
Saving cookie settings displays a properly rendered success banner
Go to /cookies and click save
> KLS-1363 fix cookie settings saved banner

- contact/templates/domestic/contact/export-support/includes/topic-landing-card.html
- contact/views.py
- tests/unit/contact/test_views.py
This PR ensures that the Digital Entry Point 'opt-in' data entered in step 8 of the triage process is only saved in the directory-forms-api database as opposed to creating a Zendesk ticket with this information.
1. Set up locally as per [this pr](https://github.com/uktrade/great-cms/pull/2659)
2. Upon completing the DPE form submission, the data from step 8 ('help us improve' and 'help us further' questions) should be present in the directory-forms-api database and _not_ in Zendesk.
> DPE-518 - Save opt-in data in database only

- international_online_offer/core/scorecard.py
Adding in hpo scoring rules for new sectors: we now support two new sectors in EYB. The mapping for the high potential opportunities has been completed and now if an investor is setting up in any of the new sectors (energy or biotech / pharma) and they are looking at specific locations they will be scored as high value due.
N/A
> Adding in hpo scoring rules for new sectors

- domestic/views/campaign.py
- tests/unit/domestic/views/test_views.py
This change addresses the the bug in Campaign pages that prevents redirects from working correctly.
> KLS-1603 fix campaign site redirects

- core/templates/core/objectives.html
This PR fixes issue whereby objectives (of type Wagtail StructBlock) were being sent directly to a richtext filter resulting in some LearnToExport pages not loading.
1. Visit a 'Learn to export' page that has objectives
2. The page does not load with the error message `TypeError: 'richtext' template filter received an invalid value; expected string, got <class 'wagtail.blocks.struct_block.StructValue'>`
3. After PR page displays correctly
> KLS-1654 BugFix on Learn to Export Page objectives

- core/urls.py
- requirements.txt
- requirements_test.txt
Redirect for Campaign site www.great.gov.uk/campaign-site/uk-advanced-manufacturing-plan to
www.great.gov.uk/AMP
Redirect for Campaign site www.great.gov.uk/campaign-site/india to
www.great.gov.uk/india
Nb: Does not work if added to urls_redirect.py
> redirect campaign site uk-advanced-manufacturing-plan

- config/settings.py
- core/middleware.py
- tests/unit/core/test_middleware.py
CONTEXT: This changeset brings missing application security headers into the global responses:
- `X-Permitted-Cross-Domain-Policies` via a custom middleware class
> Add middleware to limit data accessed on the domain and CSP

- core/templatetags/content_tags.py
A fix to add the. missed out class to signed out version of the LTE landing page descriptions on card.
> Add class to signed out users

- export_academy/views.py
- tests/unit/export_academy/test_views.py
Fixes issue where the next live event section of the past recording page displays the furthest away event rather than the next event.
To test make sure you have multiple events, each with a past recording that falls on the same date. When the past recording is opened the next event should be linked, not the last.
> Update event filter to grab the next event

- core/management/commands/eyb_import_trade_associations.py
- tests/unit/core/management/commands/test_import_eyb_data.py
Noticed that the Ids we get in the export for data workspace arent honoured. It would seem that a delete and reimport is done their side and so we cannot check exists on this id. Changing script to delete and re-import all records. No other records are bound to these Ids so is safe. 
N/A
> EYB import trade associations management command update to cater for non sequential Ids 

- .circleci/config.yml
Previous circle-ci tests failing occasionally on the install chrome drive phase - [example](https://app.circleci.com/pipelines/github/uktrade/great-cms/14884/workflows/9e372e8b-5026-4323-890f-9eb8a68a66ae/jobs/85639/parallel-runs/0/steps/0-106). 
This PR updates the circle ci browser-tools orb and also uses the latest version of chrome as opposed to a pinned version.
> update browsertools orb and use latest chrome

- export_academy/views.py
- tests/unit/export_academy/test_views.py
PR to serve a user with a 404 error when they try to visit /export-academy/{slug} with an invalid page slug as a URL path parameter.
1. Visit /export-academy/{page-slug} where {page-slug} is a valid slug of type CoursePage. The course page is displayed.
2. Visit /export-academy/{invalid-page-slug} where {invalid-page-slug} is not a CoursePage. A 404 error is presented.
> Return 404 if course page slug not found

- core/templates/components/great/radios.html
- export_academy/forms.py
- export_academy/templates/export_academy/registration_form_step2.html
- export_academy/templates/export_academy/registration_form_step3.html
The UKEA registration flow followed an implementation pattern from great-components for radio inputs which resulted in use of unordered lists / list items to represent options. This PR updates the inputs to use the design pattern suggested in the gov.uk design-system [ref](https://design-system.service.gov.uk/components/radios/) and align with the approach taken in contact Export Support.
> KLS-1791 - update markup used for UKEA registration flow

- core/templates/components/great/card.html
Currently data-title/data-location html attributes are applied to the content container div which excludes the leading image (if present). I.e. if a user clicks on the image the data attributes are not captured. This PR lifts the data attributes up into the parent div.
> IOO-1175 add data attrs to parent div

- core/templates/microsites/includes/microsite_header.html
This PR is to fix a breadcrumb in microsites that was changed last month. The new breadcrumb is:
<p>Get support for UK export or investment at  <a href="/">great.gov.uk</a></p>
> Change microsite breadcrumb back to previous version

- learn/templates/learn/detail_page.html
Great.gov Promo/Inline feedback form layout issue fixed - govuk-grid-column-full class removed from outer promo div in learn/detail_page.html, float:left was the source of layout issue
> GREAT-381-UKEA promotion box encroaching on inline feedback component

- international_online_offer/forms.py
Add max length to EYB profile form fields to prevent the user being presented with a 'Sorry there is a problem with this service' screen when their input character length exceeds the django model length.
> IOO-1334 - add max length to EYB profile form

- core/templates/components/cookie_notice.html
- core/templates/core/base.html
- lighthouserc.js
Cookie modal was not showing on the learn pages. This was due to the base template not using the new cookie confirmation banner.
> FIX - Add new cookie notice to learn base template

- core/templates/components/header_footer/footer_base.html
- core/templates/core/footer.html
- international/templates/international/footer.html
Small fix to the international homepage and campaign site footer links
> Fix footer links for privacy and cookies in base footer templates for international homepage and campaigns

- core/templates/core/page_blank.html
- learn/templates/learn/automated_list_page.html
- Update LTE landing page to use the base template meta blocks
- Include the same meta contents in page_blank.html that core/base.html has
> Include title in pages that are missing it

- export_academy/templates/export_academy/landing_page.html
CONTEXT: This changeset updates the UK Export Academy landing page template so that the position of the breadcrumbs component is displayed directly below the nav bar.
> fix: move breadcrumbs to top of webpage

- international/templates/international/index.html
Ensure font size in cards of International homeapage reduces in mobile view.
Before:
After:
> EYB 50 align typeface on international homepage in mobile view

- international_investment/forms.py
Added updated error messages to investment flow and fixed bug where selecting other does not require text input to be populated to pass validation
N/A
> Added updated error messages to investment flow

- core/static/javascript/great.password-reveal.js
- core/templates/components/great/password-show-hide.html
Very small fix to change the password input id in eauk signup/signin from 'password-input' to 'id_password' to remain in line with current id and pass test suite
> small password input box id fix for automated tests on eauk signin

- contact/templates/domestic/contact/export-support/base.html
- contact/templates/domestic/contact/export-support/feedback-confirmation.html
- tests/unit/contact/test_views.py
Ensure dep contact form pages are hidden from search engines
> ET-259: Hide dep contact form pages from search engines

- activitystream/filters.py
- activitystream/pagination.py
- activitystream/serializers.py
- activitystream/urls.py
- activitystream/views.py
Publish data on activitystream url for WTE HCSAT .
> GRTLV-211: Where to Export HCSAT - Data workspace

- core/models.py
Removes a file field as it cannot resolve to a safe migration.
> Remove file field on GreatMedia

- contact/templates/domestic/contact/routing/step-great-account.html
- contact/templatetags/contact_canonical_url_tags.py
Add canonical url to contact forms - cannot use SEOMixin as not wagtail pages
> Add canonical url to contact forms

- international/templates/international/header.html
- international_online_offer/models.py
- international_online_offer/templates/eyb/includes/step_guide.html
- international_online_offer/urls.py
- tests/unit/international_online_offer/test_views.py
Changed link on step guide to point and correct folder for article 
And
Redirect added to send user to guide if going to root of EYB when logged in
N/A
> Redirect added to send user to guide if going to root of EYB when logged in

- international/templates/international/404.html
- international/templates/international/base.html
- international/urls.py
- international_online_offer/templates/eyb/base.html
- international_online_offer/templates/eyb/index.html
- international_online_offer/templates/eyb/signup.html
- international_online_offer/views.py
This PR Adds desired padding to main section and ensures placement of breadcrumbs is outside main section to facilitate 'skip to content' functionality.
Before:
After:
> IGUK-231 - EYB accessibility - padding on main, location of breadcrumbs

- activitystream/serializers.py
- activitystream/views.py
- core/templatetags/content_tags.py
- domestic/templates/domestic/country_guide.html
- tests/unit/core/test_templatetags.py
The H1 tag in market guides is now created using the page title and a templatetag to make the country name more readable i.e.
'United Kingdom' will become 'the United Kingdom
'England' will stay as 'England'
> Adjust country names and append 'the' to countries such as 'Maldives'

- core/models.py
- learn/templates/learn/detail_page.html
- tests/unit/core/test_wagtail_hooks.py
Fix to only show csat form on first article and to stop displaying after the first submission
> Learn to Export HCSAT bug fix

- international_online_offer/templates/eyb/includes/back_link.html
- international_online_offer/templates/eyb/includes/breadcrumbs.html
Small PR to change the font-size of EYB back and breadcrumb buttons to 16px and 14px on mobile.
> IGUK-192 - amend breadcrumb/backlink font size

- export_academy/urls.py
- export_academy/views.py
This ticket fixes a bug on the Events listing cache where users were seeing events as Booked. It ensures caching is only done on a per-user basis (by Cookie).
> Cache events by user

- search/templates/search_opensearch.html
- search/urls.py
- search/views.py
- tests/unit/search/test_views.py
This ticket adds hooks the frontend /search page up tot he Opensearch backend.
> Greatuk 877 feature integrate opensearch into searchpage

- .circleci/config.yml
- international_buy_from_the_uk/forms.py
- international_buy_from_the_uk/models.py
- international_buy_from_the_uk/templates/buy_from_the_uk/index.html
- package-lock.json
- package.json
Adding industries dropdown to buy from the UK index page which allows users to select a industry to pre-populate the search when navigating to find a supplier search for companies.
N/A
> IGUK-416 Feature adding industries dropdown to buy from the UK index

- export_academy/helpers.py
- export_academy/templates/export_academy/event_details.html
What
- Hide cta "Book event"(logged in ) and "Sign up to book event" (logged out) for In person events. These are for ITW
Why
- We want ITW in person events to be booked through external links which will be added in the events details , hence we want to avoid confusion by hiding the Button to book events through great.
Should be able to see it for Online events
> GRTLV-353 : Hite CTA for in person events for ITW

- config/settings.py
A bug was preventing access to learn to export articles which are accessed with opensearch, and affected local, dev and staging (dev/staging use aws whereas prod/uat still use gov-paas). This was introduced during a change to support the AWS migration, and the deleted connection setup has been re-added in this PR. 
Error reporting on local:
Error reporting on dev/staging:
After fix:
> Grtlv 360 bug preventing access to learn to export articles on staging dev local environments

- activitystream/views.py
Change the Base View to update query_set based on "id"
Issue caused when pagination happens in DAG :
https://data-flow.data.trade.gov.uk/dags/WhereToExportCsatFeedbackDataPipeline/grid?dag_run_id=scheduled__2024-10-05T00%3A00%3A00%2B00%3A00&task_id=fetch&tab=logs
> GRTLV-366: Update Base View to query by id

- core/views.py
Removes no_cache decorators from guided journey view
Cloudfront mis configuration has been resolved
> ET-517: guided journey - remove caching

- international_online_offer/templates/eyb/triage/find_your_company.html
Sets the max. length on the Company Lookup autocomplete to 30 characters. 
Calling the Dun and Bradstreet typeahead API with more than 30 characters results in an `HTTP 400 bad request` error. For example, [this Sentry error](https://sentry.ci.uktrade.digital/organizations/dit/issues/135362/?environment=prod&project=173&referrer=alert_email).
In a PR without this fix, e.g. UAT, navigate to `international/expand-your-business-in-the-uk/find-your-company`. Enter more than 30 characters. No error will be visible in the UI but will throw an error server-side which is captured by Sentry.
> IGUK-477 set max length on autocomplete

- international_online_offer/templates/eyb/triage/find_your_company.html
Only send the first two characters of a supported Country code to the Dun and Bradstreet typeahead API. Addresses this [Sentry error](https://sentry.ci.uktrade.digital/organizations/dit/issues/135362/activity/?project=173&referrer=RegressionActivityEmail).
Some of the ISO-2 codes of Countries supported within EYB contain > 2 characters, for example `('AE-AZ', 'Abu Dhabi')`. The Dun and Bradstreet Typeahead API returns a `400 bad request` error when > 2 characters are sent in the `countryISOAlpha2Code` query parameter. The recommendation from Dun and Bradstreet is that in these scenarios we simply send the first two characters [source](https://directplus.documentation.dnb.com/html/resources/CountryCodes.html).
A [tech. debt ticket]( https://uktrade.atlassian.net/browse/IGUK-477) has been …
> IGUK-477 bug fix on typeahead for countries with an ISO code > 2 chars

- core/fixtures/market-guide-sector-tags.csv
- core/management/commands/ingest_market_guide_sector_tags.py
- domestic/fixtures/markets_filtering_fixtures.json
- domestic/models.py
- domestic/templates/domestic/topic_landing_pages/markets.html
- pii-secret-exclude.txt
- tests/unit/domestic/test_models.py
This PR updates the markets landing page to use the new region tag and trade bloc tag fields on the country guide page model. This is a simple extension of the original implementation.
The new list of official region tags is much shorter and is missing redundant regions like Antarctica. And the trading bloc filters allow users with a trading bloc in mind to narrow down results that way.
> New region and trading bloc filters

- core/management/commands/combine_hcsat.py
update to management command to persist original created timestamp from old hcsat tables into new one
The creation of the new table entry was overwriting the previous 'created' date and making it seem in reporting like all hcsat's came in on the same day and impacting quarterly progress reporting. This will fix that issue. 
> Fix HCSAT combine command to persist original creation date

- core/templates/microsites/includes/microsite_detail_content.html
Add ltr direction for div containing hero video play button
In rtl direction (arabic version of the site) the play button is malformed
> GRTLV-383-ltr direction added for play button

- core/helpers.py
Only show bookable ukea events to users
So that users only see ukea events they can attend
> ET-551: guided journey - ukea events only future events

- international_online_offer/services.py
- tests/unit/international_online_offer/test_services.py
Small bugfix for [this PR](https://github.com/uktrade/great-cms/pull/3607). Related [Sentry error](https://sentry.ci.uktrade.digital/organizations/dit/issues/138874/?environment=dev&project=173&referrer=alert_email).
In this line: https://github.com/uktrade/great-cms/blob/133d0526300229d5284d5438fbd37d384810d711/international_online_offer/views.py#L310 we call the `get_country_display_name` method which in turn makes an api request to get the display name of a country given an ISO2 code. There is an edge case whereby a user signs up with a regular Great account and navigates to EYB. In this case they do not have a UserData object and so the api is called with an empty string which returns a 404. This bug fix handles this scenario gracefully.
> IGUK-381 return empty string if country not found

- core/static/javascript/dit.tagging.js
- core/templatetags/video_tags.py
- tests/unit/core/test_templatetags.py
Google Tag Manager needs to capture the percent of video , status and title when a user performs any action with the video on the pages.
Needed to analyse where user is stopping / watching the EA event videos.
> Feature grtlv 364 add values data layer

- international_online_offer/views.py
Bug fix on country not displaying on company manual entry screen.
Before:
After:
> bug fix on country not displaying on manual entry screen

- config/settings.py
Re-add unsafe-unline to csp_script_src in settings.py
After making this initial change, inline js (react, signout etc) stopped working, so code refactors will be needed to move code out of insecure inline js before this change is re-introduced. 
> re-add unsafe-unline to csp_script_src to re-enable inline js on site

- .gitignore
- config/env.py
- config/settings.py
We have had a lot of sentry logs with "Error: Host is not on the safe list for international URL". This is an issue from when we implemented pydantic as the env.py file is not parsing a comma separated string to a list correctly.
log example: https://sentry.ci.uktrade.digital/organizations/dit/issues/106309/?end=2024-11-09T22%3A00%3A59&environment=prod&project=173&query=is%3Aunresolved&start=2024-11-09T19%3A00%3A00&utc=true
Fixing this bug will stop this issue for Users and in Sentry
> adjusted safehosts to convert comma seperated string to a list

- core/management/commands/migrate_historic_international_hcsat.py
Migrate old International CSAT records to Domestic HCSAT.
A previous [PR](https://github.com/uktrade/great-cms/pull/3678) aligned the International CSAT with the implementation in Domestic. Prior to this alignment an International-specific version of CSAT was in production. This PR introduces a management command to migrate the old responses to the new data model.
* Note: this is 'throw-away' code, after the management command has been executed in all environments a subsequent PR will be created to remove it from the codebase.
- Create a CSAT record in `international_online_offer.csatfeedback` table
- Run the command by `make manage migrate_historic_international_hcsat`
- The record should now be visible in `core_hcsat` data table.
> IGUK-498 management command to migrate old International csat to Domestic HCSAT

- learn/templates/learn/detail_page.html
Initially hide hcsat on LTE articles, then show in js
Caching issues prevent this form from working on cached pages until a hcsat refactor can be performed. M&E have confirmed it's suitable to hide hcsat for only non-js users on these articles which is more suitable than uncaching all article pages. 
> hide LTE HCSAT for non-javascript users

- core/templatetags/content_tags.py
- domestic/templates/domestic/includes/streamfield.html
- tests/unit/domestic/test_templatetags.py
Adding a convert_anchor_identifiers_to_span filter which can be used on streamfields to convert anchor identifiers within content snippets into spans. When not used in a snippet this already occurs as intended, but the render_a method in core/rich_text.py does not fire when the anchor is used within snippets. 
Anchor identifiers in content snippets are being returned to the wagtail page as <a> tags, introducing unwanted styling and functionality to text which should only have an additional id. 
Screenshots: 
Before: 
After: 
> Bug grtlv 402 snippet headers appearing as hyperlinks in content modules

- core/context_processors.py
- sso_profile/templates/business_profile/profile.html
Link to view a business profile in find-a-supply leads to 404
We need to fix the url to the correct location in international.
I have added a new variable to the main context processor to give access to the project base_url. This will become useful in the near future when we clean up the templates.
To test:
1. create a new user
2. create a business profile
3. add a description
4. visit your directory-api instance admin url and manually verify the new business profile
5. return to the business profile in great and refresh the page. You should now see the 'View find a supplier' link
6. clicking the link should redirect you to the correct profile in /international
> Added base_url to context processor to use in profile.html

- international_online_offer/core/helpers.py
Bug IGUK-777 Fixing workflow to send user to start of EYB triage when triage or user data null
Issue found when user_data or triage_data is null. Sending user to business sector has unexpected issues. Sending user to start of triage in all situations fixes problems.
> Bug IGUK-777 Fixing workflow to send user to start of EYB triage when triage or user data null

- international_online_offer/templates/eyb/base.html
- international_online_offer/templates/eyb/triage/find_your_company.html
- international_online_offer/views.py
When a user who registered pre-Dun and Bradstreet integration (03/10/24) signs-in they are redirected to the company lookup screen with a 'more information needed' banner.
We currently redirect users who entered their company details manually (before we introduced the D&B lookup) to the D&B look up question, to either search the D&B lookup for their company information or to enter more manual details (address), so their EYB record can be ingested by Data Hub.
However, we do not explain to users why we are displaying this question when they sign back in. We need to give them better [visibility of system status](https://www.nngroup.com/articles/ten-usability-heuristics/#toc-1-visibility-of-system-status-1) so the service is predictable and trustworthy.
> IGUK-753 Show more info needed banner

- core/wagtail_hooks.py
…regardless of edits or republishing, campaign sites will now expire one year since last published
A bug was introduced a year ago, which has set the expiry date of all campaign sites as a year after they were published, or if they are old campaign sites then they will expire very soon (a year from their first publish after the bug was introduced 28/2/24). 
Some campaign sites have already expired, which prevents access to these pages. This includes pages with paid marketing leading to them, so stakeholders are keen to get this fixed as soon as possible. Manually republishing does not reset the expiry, so stakeholders have no way to restore the pages without taking a fresh copy which impacts SEO. 
Prevent campaign sites from expiring when we do not want this to occur. 
_Tick or delete as …
> bugfix: Fix campaign sites expiring after a year from first publish

- international_online_offer/core/scorecard.py
- tests/unit/international_online_offer/test_scorecard.py
Bug fix on scorecard calculation for upper thresholds in spend/labour hire.
The maximum values that a user can choose for spend is £5m+ and labour 21+. The previous implementation took the value before the '+' and used that when determining if a proposal was high or low value. This worked well for most sectors, however, some sub sectors such as 'Airports' have a GVA banding greater than £5m/21 employees. In these cases a proposal was incorrectly scored as low value.
> IGUK-936 bug fix on scorecard calculation for upper threshold

- export_academy/views.py
When you are on an event details page for a closed event. It Should not allow you to register for the event .
Registration for closed events should not be allowed. The Bug allowed users to go through ukea registration and then book onto the event even after the event was closed. This happened for already registered users as well .
**BEFORE**
**AFTER**
> GRTLV-576: SignIn redirection to watch events

- package.json
Set specific version of design system instead of latest
Avoid any changes not debugged in latest version of design system from pushing to great until tested
> fix design system import to use specific version instead of latest

- config/env.py
set directory_forms_api_default_timeout to 30s
HCsat feedback push to forms-api timing out
> Bump forms-api timeout to 30s

- activitystream/filters.py
- activitystream/pagination.py
- activitystream/serializers.py
- activitystream/urls.py
- activitystream/views.py
- tests/unit/activitystream/test_serializers.py
Add back HCSAT AS code
Timing out in Prod (okay in DEV and UAT)
> Add back HCSAT AS as timing out in Prod

- domestic_growth/templates/guide-child.html
Fixes issue with child page nav item for showing as active
To show users which child page is active
> BGST-174: fixes child page navigation active item

- domestic_growth/helpers.py
- domestic_growth/models.py
- domestic_growth/static/js/trade-associations.js
- domestic_growth/templates/guide.html
- tests/unit/domestic_growth/test_helpers.py
Adds refined display logic for trade associations based on sector and sub sector
To show most appropriate TAs to the user
> BGST-178: trade association result logic

- core/static/javascript/great.make-or-do-search-enhanced.js
Amend hint text on sector lookup by replacing 'e.g:' with 'For example,'
Stakeholder request
> GRTLV-708 amend hint text

- core/templates/core/base.html
- core/templates/microsites/base.html
- domestic/templates/domestic/base.html
- international/templates/international/base.html
add current_url tag to check to prevent it from being null
Footer wasn't rendering in hotfix bgs site
> current_site wagtail tag added to footer url check

- international/templates/international/contact.html
- international/templates/international/contact_success.html
- international/views.py
The FAs HCSAt isnot being shown in production . 
This is because when a new View was created , the HCSAT wasn't moved with it . The update to teamplate and view to move the HCSAt to the correct place.
> GRTLV-675: Move hcsat to ContactSuccessView from ContactView

- domestic_growth/helpers.py
- domestic_growth/models.py
- domestic_growth/views.py
- tests/unit/domestic_growth/test_helpers.py
Introduces a helper function that returns a view URL of the next triage question where a user has not answered the complete triage.
For use in navigation components when the user tries to access the Guide URL.
> Feature BGST-171 redirect user to triage drop off point

- domestic_growth/models.py
A quick patch to ensure the `session_id` is persisted in internal dynamic guide links. This is a short-term fix as we probably don't need postcode and sector encoded as QS params.
Content was only displaying once.
> patch for dac audit on content only displaying once

- export_academy/management/commands/delete_ukea_data.py
Request from User to delete their data from GREAT . 
Most of the data held can be deleted using the archive_user management command in directory-sso but UKEA data is help standalone . This management command will delete that data based on the user email address 
> Add a management command to delete UKEA data based on user email

- domestic_growth/forms.py
- domestic_growth/templates/existing-business/triage-sector.html
- domestic_growth/templates/starting-a-business/triage-sector.html
- tests/unit/domestic_growth/test_forms.py
1. Enforce mutually exclusive sector selection options
2. When a user clears the sector autocomplete ensure it is considered as an empty input instead of reverting to the previously entered sector
Raised as BGS QA item
> BGST-375 bug fixes on sector select

- core/models.py
- domestic/views/campaign.py
- tests/unit/core/test_models.py
Campaign site menu links should reflect the request domain
Page links must be for the domain user is using in a multi-site setup so they are not navigated to a different site.
> Bug greatuk 1769 microsite menu links not working with multi site

- domestic/templates/domestic/base.html
- international/forms.py
- international/templates/international/contact.html
- international/templates/international/includes/contact_success.html
- international/views.py
Makes some content changes to remove references to great.gov.uk in the contact forms in line with the URL change
To prepare for the business growth service launch
This change also removes breadcrumbs for the exporting landing page in line with designs
The feature flag FEATURE_DOMESTIC_GROWTH is used to prevent the new url from being leaked prior to the release of the new site, the rest of the content changes are not behind a flag.
> Remove breadcrumbs for export homepage and content changes

- core/models.py
Makes export support pages work in new BGS url structure
To allow for proposed new url structure for export support pages
> BGST-417: Make export support pages work in new bgs url structure

- .copilot/image_build_run.sh
Fixes failing build whilst maintaining functionality for comments, e.g. `#  /PS-IGNORE` to be in environment file.
Pre-commit secret hooks flagged potential secrets which was resolved via adding `#  /PS-IGNORE` in [this PR](https://github.com/uktrade/great-cms/pull/4064). This broke the build script / automated deployment as comments could not be parsed. This PR adds code to rectify as recommended in [this Slack request](https://ditdigitalteam.slack.com/archives/C070P5A4EV8/p1746520764392149).
> BGST-409 fix dev deploy failing

- core/static/javascript/digital-entry-point.js
Updates DSS tracking JS to work after export support url changes
Ensure custom tracking still works after url changes
> BGST-417: JS changes after export support url changes

- domestic/views/campaign.py
- tests/unit/core/test_views.py
- tests/unit/domestic/views/test_views.py
Bug on campaign site pages : Any changes are published live on CMS but changes are not reflected on the live page 
Due to multisite the live pages are linking to the BGS cms pages . The change makes sure the pages are picked up from the correct root site.
> Update campaign site pages to get the current page from the root site

- domestic_growth/helpers.py
- domestic_growth/views.py
Refactor use of exception when checking if a triage record exists.
1. Using exceptions for a normal user journey results in increased noise in Sentry.
2. Refactor to a more typical django pattern.
We are using `bool(queryset)` rather than `exists()` to avoid querying the database twice as per [docs](https://docs.djangoproject.com/en/5.2/ref/models/querysets/#exists)
> BGST-375 refactor use of exception for getting triage data

- international_online_offer/models.py
EYB articles are exposed in the template using article.url. When getting the articles to show via the django query we need to cater for the fact that in doing multi site for BGS there are duplicate articles sitting in wagtail (BGS root and domestic). The reason in some cases the wrong .url is shown in the ui is beacuse the query gets the first article it finds and not the one for the section of wagtail its stored in. This code will use the parent / child setup to ensure the correct article is surfaced.
Bug in Prod
> bug GREATUK-1992 EYB article links not aware of BGS

- international_online_offer/models.py
- international_online_offer/templates/eyb/includes/dynamic-guide/salary_data.html
This PR addresses Hide salary component when one of the levels are not present
Feature IGUK-971 Hide salary component when missing data in the levels
> Hide salary component when either one of the levels are not present

- core/models.py
- domestic/urls.py
This ticket resolved a bug in learn to export where duplicate links are being shows for duplicate bgs / non bgs pages.
> Bug greatuk 1786 duplicate learn to export topics

- core/forms.py
- core/templates/core/business_growth_contact.html
Using the design system form widgets to fix the styling of the get-help
To help get get-help ready to help people get help
this fixes:
- incorrect height on form fields
- tabindex not be correctly set on form errors 
> implemented ds form widgets on get-help

- config/celery.py
- domestic_growth/helpers.py
- domestic_growth/management/commands/move_triage_data_from_cache_to_db.py
- domestic_growth/tasks.py
- domestic_growth/views.py
- tests/unit/domestic_growth/test_commands.py
- tests/unit/domestic_growth/test_views.py
1. Triage data is stored in the cache as the user progresses
2. On the final question for each triage the answers are moved from the cache and persisted in the db
3. A management command is scheduled to run daily that will take partially completed triage responses and persist in db
4. To further reduce db load, the db is only queried on form initialisation if an `edit=true` query parameter exists.
DB load raised as high-priority item in BGS threat modelling report.
Normal flow
1. Start BGS triage
2. Complete first question
3. Connect to redis
4. View keys - you should see a key in the format e.g. '1:bgs:StartingABusinessTriage:{triage_uuid}
5. View data for key - it should be a dictionary with the answer to the first question
6. Complete the triage
7. Key from point 4 should now not be …
> BGST-430 use caching for triage data

- international/models.py
- tests/unit/international/test_models.py
Allow International / Invest in UK to be a child of the BGS landing page.
So international and its child services can be moved in wagtail UI
> bug-GREATUK-2107-allow-invest-child-of-bgs-landing

- contact/templates/domestic/contact/export-support/includes/market-widget.html
Make guide journey results page market widget url conditional for bgs
Broken url for market page
> GREATUK-2194: use reelative path for bgs guide journey results page market widget

- domestic_growth/templates/includes/_render-snippet.html
Only show static snippets tagged with region or sector if they match business region or sector
Only show relevant content on bgs guide pages
> BGST-442: Regional static snippets
