config/settings.py
=> add AWS_S3_HOST

config/settings.py, core/templates/core/base.html, domestic/templates/domestic/domestic_home_page.html, requirements.in, requirements.txt, requirements_test.txt
=> add homepage mock FE

README.md, domestic/management/commands/bootstrap_great.py, tests/domestic/test_bootstrap_great.py
=> create superuser on bootstrap

CHANGELOG.md, config/settings.py, core/helpers.py, tests/core/test_helpers.py
=> Mvp 228 duties url

CHANGELOG.md, manifest.yml, tests/browser/test_export_plan_dashboard.py
=> V3 cipipeline

CHANGELOG.md, exportplan/helpers.py, exportplan/templates/exportplan/partials/_country-stats.html, exportplan/templates/exportplan/sections/target-markets.html, exportplan/urls.py, exportplan/views.py, tests/browser/common_selectors.py, tests/browser/test_export_plan_about_your_plan.py, tests/browser/test_export_plan_target_markets.py, tests/unit/exportplan/test_helpers.py, tests/unit/exportplan/test_views.py
=> MVP-360 - add muliple markets

CHANGELOG.md, config/settings.py, core/middleware.py, core/models.py, makefile, requirements.txt, requirements_test.txt, tests/unit/core/test_middleware.py
=> Prevent learn caurosel twice

CHANGELOG.md, config/settings.py, core/helpers.py, core/views.py, exportplan/context.py, exportplan/forms.py, exportplan/templates/exportplan/export_plan_dashboard_page.html, exportplan/templates/exportplan/includes/sidebar.html, exportplan/templates/exportplan/logo-form.html, exportplan/urls.py, exportplan/views.py, requirements.in, requirements.txt, requirements_test.txt, tests/browser/test_export_plan_target_markets.py, tests/browser/util.py, tests/unit/core/test_rules.py, tests/unit/exportplan/test_views.py, tests/unit/sso/test_views.py
=> MVP-450- add image upload feature

requirements.in, requirements.txt, requirements_test.txt
=> Upgrade markdown2

.circleci/config.yml, CHANGELOG.md, README.md, makefile, requirements_test.in, requirements_test.txt, tests/load/mvp_home.py
=> Fix locust breaking changes

CHANGELOG.md, exportplan/templates/exportplan/logo-form.html
=> GP2-67 fix href

CHANGELOG.md, exportplan/templates/exportplan/dashboard_page.html, exportplan/templates/exportplan/includes/sticky-header.html
=> Add personalisation bar to export plan

CHANGELOG.md, exportplan/helpers.py, exportplan/views.py, tests/unit/exportplan/test_helpers.py, tests/unit/exportplan/test_views.py
=> GP2-154 change country lists

CHANGELOG.md, core/templates/core/curated_topic.html, learn/templates/learn/curated_list_page.html, tests/browser/common_selectors.py
=> Fix numbers on curated list page

README.md
Just testing CI trigger on develop
=> Updated Readme make command to align with makefile

exportplan/forms.py
=> add business performance

CHANGELOG.md, core/blocks.py, core/templates/core/cs_block.html, tests/unit/core/test_blocks.py, tests/unit/domestic/factories.py
=> (GP2-218) Added RichText filtering to render richtext to content modules

CHANGELOG.md, exportplan/templates/exportplan/section.html
=> back to Export plan fix

CHANGELOG.md, learn/templates/learn/detail_page.html
=> GP2-79 - Update lesson heading styling

CHANGELOG.md, learn/templates/learn/detail_page.html
=> GP2-252 - Lesson objectives

exportplan/templates/exportplan/sections/marketing-approach.html, react-components/setupJest.js, react-components/src/Helpers.js, react-components/src/components/Fields/InputWithDropdown/InputWithDropdown.test.jsx, react-components/src/components/Fields/InputWithDropdown/index.jsx, react-components/src/components/RouteToMarket/RouteToMarket.jsx, react-components/src/components/RouteToMarket/RouteToMarket.scss, react-components/src/components/RouteToMarket/RouteToMarketSection/index.jsx, react-components/tests/Helpers.test.js
=> Gp2 194 route to market component

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.in, requirements_test.txt
=> Dependencies upgrade

CHANGELOG.md, exportplan/data.py, exportplan/templates/exportplan/sections/adaptation-for-target-market.html, exportplan/urls.py, exportplan/views.py
=> create adaptation for target market page

core/middleware.py
- [N/A] Change has a jira ticket that has the correct status.
- [N/A] Changelog entry added.
Tiny fix to stop error in wagtail editor
=> No-ticket_fix_for_wagtail_editor

CHANGELOG.md, domestic/templates/domestic/domestic_dashboard.html
- [Y] Change has a jira ticket that has the correct status.
- [Y] Changelog entry added.
=> GP2-382_remove_welcome_email

CHANGELOG.md, core/templates/core/step_by_step.html, learn/templates/learn/detail_page.html
=> GP2-396 - Lesson - page structure

CHANGELOG.md, learn/templates/learn/detail_page.html
=> Fix for rendering page

exportplan/forms.py, exportplan/templates/exportplan/sections/adaptation-for-your-target-market.html, exportplan/views.py
=> GP2-368-replace hard coded data with django forms

CHANGELOG.md, learn/templates/learn/recap.html
=> Recap field rendering as rich text

CHANGELOG.md, domestic/helpers.py, domestic/templates/domestic/dashboard_cards/learning_progress.html, tests/browser/test_lessons.py, tests/unit/core/test_views.py
=> Gp2 336 change dashboard progress to curated list page

CHANGELOG.md, exportplan/templates/exportplan/sections/adaptation-for-your-target-market.html, exportplan/views.py
=> GP2-362-factbook-language-display

core/templates/core/includes/_route-section.html, domestic/templates/domestic/dashboard_cards/events.html, domestic/templates/domestic/dashboard_cards/export_opportunities.html, domestic/templates/domestic/dashboard_cards/learning_progress.html, domestic/templates/domestic/dashboard_cards/new_markets.html, domestic/templates/domestic/dashboard_cards/tariffs.html, domestic/templates/domestic/domestic_dashboard.html
No ticket
Restore dashboard heading sizes
=> Fix_dashboard_headings

CHANGELOG.md, package-lock.json, package.json
=> Upgraded node-fetch package

pull_request_template.md
Mainly to make it easy to add a clear link to Jira, for reviewers' convenience, but also a couple of other nice-to-haves
=> Minor update to the PR template

learn/templates/learn/detail_page.html
=> Added missing image for next module in DetailPage

CHANGELOG.md, core/models.py, learn/templates/learn/detail_page.html, tests/unit/core/test_utils.py
=> Bugfix: Next lesson image fix

exportplan/templates/exportplan/dashboard_page.html
=> update dashboard headers

CHANGELOG.md, learn/templates/learn/automated_list_page.html
=> GP2-429 - Remove old unused content from learning homepage

CHANGELOG.md, exportplan/templates/exportplan/sections/objectives.html
=> add-learning-to-objectives

exportplan/templates/exportplan/sections/about-your-business.html
=> add second learn linking component to about your business page

exportplan/templates/exportplan/sections/marketing-approach.html, exportplan/templates/exportplan/sections/objectives.html
=> update objectives and marketing approach templates

react-components/src/components/Dashboard/Dashboard.test.jsx, react-components/src/components/Dashboard/index.jsx, react-components/src/components/Sidebar/Sidebar.test.jsx
=> add unit test for dashboard component and update sidebar

CHANGELOG.md, core/templates/core/objectives.html, tests/unit/core/test_wagtail_hooks.py
=> GP2-755: Add objectives section title

CHANGELOG.md, learn/templates/learn/automated_list_page.html
=> GP2-707 - Change button size from small to medium

core/templates/core/base.html
=> Feature_flag_search_no_login

README.md
remove prettier reference
update env vars names
=> bring readme up to date

CHANGELOG.md, core/templates/core/case_study_block.html
=> GP2-451 - Layout tweaks to case study

CHANGELOG.md, requirements.in, requirements.txt
=>  GP2-699-swamp-route-to-market-constants

domestic/templates/domestic/dashboard_cards/export_opportunities.html
Hello spelling change, hopefully this is helping
=> Updating buyer to buyers

CHANGELOG.md, core/sass/_base.scss, domestic/templates/domestic/domestic_home_page.html, package.json, react-components/src/components/Form/FormGroup/index.jsx, react-components/src/components/Form/Input/Input.test.jsx, react-components/src/components/Form/Input/index.jsx, react-components/src/components/Form/TextArea/index.jsx, react-components/src/components/SocialLoginButtons.jsx, react-components/src/views/LoginModal/Step1.jsx, react-components/src/views/Signup/Component.jsx, react-components/src/views/Signup/StepCredentials.jsx, react-components/src/views/Signup/StepSuccess.jsx
=> GP2-735 update login styling, code refactor

CHANGELOG.md, learn/templates/learn/detail_page.html
=> GP2-451 - Remove redundant step by step block

CHANGELOG.md, core/templates/core/curated_topic.html
=> GP2-162 - Add missing clock icon to lesson

CHANGELOG.md, core/templates/core/curated_topic.html
=> GP2-162 - Fix empty span

domestic/templates/domestic/domestic_dashboard.html
=> Skip suppressing GTM container on domestic dashboard

CHANGELOG.md, core/templatetags/progress_bar.py, domestic/templates/domestic/dashboard_cards/learning_progress.html, tests/browser/common_selectors.py, tests/unit/core/test_templatetags.py
=> GP2-878 Dashboard progress bar styling

exportplan/templates/exportplan/sections/marketing-approach.html
=> add data not available - footnote

CHANGELOG.md, domestic/templates/domestic/domestic_dashboard.html
=> GP2-763 Analytics - first sign-in

CHANGELOG.md, exportplan/templates/exportplan/dashboard_page.html
=> GP2-940 Deletion of "Add your business name"

CHANGELOG.md, core/templates/core/target_markets.html, core/urls.py, core/views.py, exportplan/templates/exportplan/section.html, tests/unit/core/test_views.py
=> GP2-917 Target market page

exportplan/templates/exportplan/sections/business-objectives.html
=> remove textarea resize script

CHANGELOG.md, exportplan/templates/exportplan/dashboard_page.html
=> GP2-926 update copy

exportplan/templates/exportplan/sections/target-markets-research.html
=> GP2-629 update page structure

core/models.py, core/utils.py, core/wagtail_hooks.py, domestic/helpers.py, learn/templates/learn/curated_list_page.html, tests/browser/conftest.py, tests/browser/test_dashboard.py, tests/browser/test_lessons.py, tests/unit/conftest.py, tests/unit/core/factories.py, tests/unit/core/test_middleware.py, tests/unit/core/test_models.py, tests/unit/core/test_utils.py, tests/unit/core/test_views.py, tests/unit/core/test_wagtail_hooks.py, tests/unit/domestic/test_helpers.py, tests/unit/domestic/test_models.py, tests/unit/exportplan/test_helpers.py, tests/unit/learn/test_models.py
Here's another changeset of updates as part of the topic refactor. There are lots more to come but am trying to PR whenever tests are passing to make review easier.
=> GP2-884  refactor topic modelling  part two helper code

core/helpers.py, core/templates/core/curated_topic.html, core/templatetags/content_tags.py, learn/templates/learn/curated_list_page.html, tests/unit/core/test_models.py, tests/unit/core/test_templatetags.py, tests/unit/core/test_utils.py, tests/unit/core/test_wagtail_hooks.py
More refactoring focusing on the template tags used for showing progress
=> GP2-884 - Refactor topic modelling - template tags

core/models.py
=> GP2-884: fix up serve_preview - was missing a param in its signature

CHANGELOG.md, core/templates/core/login.html
=> gp2-693-hide-footer-login

CHANGELOG.md, core/templates/core/signup.html
=>  GP2-1022-hide-footer-sign-up

exportplan/templates/exportplan/sections/costs-and-pricing.html
=> GP2-283 update content

CHANGELOG.md, exportplan/views.py
=> GP2-1146 - fix broken forms

CHANGELOG.md, sso/views.py, tests/unit/sso/test_views.py
=> [Bugfix] [GBAU-869] Terminate SSO session on logout

react-components/src/components/Form/FormGroup/FormGroup.test.jsx, react-components/src/components/Form/FormGroup/index.jsx
=> GP2-1107 add unit tests - formGroup component

CHANGELOG.md, package-lock.json
Also, backported hotfix from release to develop
=> Post release changelog update

CHANGELOG.md, react-components/dist/magna.js, react-components/src/components/CompareMarkets/SelectMarket.jsx
CONTEXT: This PR enables the tracking of the country a user selects out of the countries in the comparison list.
=> [GP2-1171] Track country selection from comparison list

CHANGELOG.md, core/helpers.py
Small bugfix which were preventing to multiple API call
=> Bugfix for compare countries where API failing to load data

exportplan/templates/exportplan/sections/costs-and-pricing.html
=> fix-c-and-p-ep-page

CHANGELOG.md, core/blocks.py, domestic/migrations/0008_drop_markdownfield_usage.py, domestic/migrations/0011_gcp_move_accordions_to_streamfield.py, domestic/models.py
Minor fixups of labelling inside the CMS pages. Amended the existing migrations rather than creating new ones, because the changes made here do not require a DB schema change
=> GP2 1366 and GP2 1367: Minor fixups

exportplan/helpers.py, exportplan/views.py, tests/unit/exportplan/test_helpers.py, tests/unit/exportplan/test_views.py
=> GP2-1240-EP-progress

core/templates/core/compare_countries.html
=> Change hero copy

core/templates/core/compare_countries.html
Fix hero copy in 'where to export' section
=> Fix where to export hero copy

exportplan/templates/exportplan/sections/marketing-approach.html
=> remove null breaking tooltip

CHANGELOG.md
=> Release 1.2.0 CL update

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
-  [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)
=> Django security update

core/models.py
=> CS scoring backend admin UI improvement

README.md
=> Add BAU FE notes to readme

CHANGELOG.md, core/blocks.py, core/models.py, core/utils.py, tests/browser/test_lessons.py, tests/conftest.py, tests/unit/core/test_blocks.py
This changeset adds additional calculation for the case study to appear on the Lesson page.
=> Added ranking calculation for case study

core/models.py
This is bugfix after amending setting field name
=> Fix field name

exportplan/api.py, exportplan/serializers.py, exportplan/urls.py, exportplan/views.py, requirements.in, requirements.txt, requirements_test.txt, tests/conftest.py, tests/unit/exportplan/test_ajax.py, tests/unit/exportplan/test_serializers.py, tests/unit/exportplan/test_views.py
=> GP2-1181-business-risk

react-components/src/components/GettingPaid/GettingPaid.test.jsx
add unit tests for the getting paid page
=> add unit tests for the getting paid page

CHANGELOG.md, cms_extras/modeladmin.py
This changeset adds extra search fields while looking up case study admin UI
=> Added extra field for search ability for case study admin UI

CHANGELOG.md, domestic/models.py
- [x ] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-1784
--
- [ x] Jira ticket has the correct status.
- [x ] [Changelog](CHANGELOG.md) entry added.
=> Stop breadcrumbs showing for structural page

CHANGELOG.md
Couple of things in the wrong place
=> Minor changelog cleanup on develop

CHANGELOG.md, domestic/models.py
This hotfixes `release` with the fixup made to develop in https://github.com/uktrade/great-cms/pull/1001
=> Hotfix/gp2 1784  breadcrumbs on structural page

docs/conf.py
Micro change removing mention of w-p from a docs source file (which doesn't look like it had a compiled version in the codebase, so only one file changes)
=> GP2-1483: Remove reference to wagtail-personalisation from docs

core/static/cms-admin/css/case-study-index.css, core/templates/modeladmin/index.html, core/wagtail_hooks.py
This changeset is style tweak from the previous PR for case study admin UI
=> Added CSS for case study admin UI style tweak

CHANGELOG.md, core/models.py, domestic/models.py, tests/unit/core/test_models.py, tests/unit/domestic/test_models.py
No migration/schema change here, but some test updates
=> GP2-1832: Update allowed-parent rules so we can swap old homepage for new

config/utils.py, tests/unit/config/test_utils.py
Applying configuration for wagtail transfer from staging to Beta
=> Applying wagtail configuration for staging to beta content transfer

CHANGELOG.md, domestic/templates/domestic/topic_landing_pages/markets.html
Add magna banner on markets homepage
=> Add magna banner on markets homepage

domestic/templates/domestic/domestic_dashboard.html
=> fix-button-labels

CHANGELOG.md, domestic/templates/domestic/includes/article_detail_content.html
Fixes url used in article page banner
=> GP2-1775: Fix warning banner url

domestic/templates/domestic/article_listing_page.html, domestic/templates/domestic/country_guide.html, domestic/templates/domestic/topic_landing_pages/generic.html, domestic/templates/domestic/topic_landing_pages/markets.html
Simple fixes for previous incorrect CTA banner links
=> Banner CTA and layout fix

requirements.in, requirements.txt, requirements_test.txt
=> Bumping wagtail-transfer package

domestic/templates/domestic/article_listing_page.html, domestic/templates/domestic/country_guide.html, domestic/templates/domestic/topic_landing_pages/generic.html, domestic/templates/domestic/topic_landing_pages/markets.html
=> Remove banner logged out condiional and fix incorrect link

config/settings.py, core/migrations/0001_squashed_0038_add_image_and_video_to_lesson_body.py, requirements.in, requirements.txt, requirements_test.txt, tests/conftest.py, tests/helpers.py, tests/unit/cms_extra/test_modeladmin.py, tests/unit/core/test_helpers.py, tests/unit/core/test_models.py, tests/unit/core/test_templatetags.py, tests/unit/domestic/test_helpers.py, tests/unit/domestic/test_models.py, tests/unit/sso/test_helpers.py
This changeset upgrade wagtail to 2.11.*
=> Wagtail upgrade 2.11

domestic/templates/domestic/article_listing_page.html, domestic/templates/domestic/country_guide.html, domestic/templates/domestic/topic_landing_pages/generic.html, domestic/templates/domestic/topic_landing_pages/markets.html
Banner auth requirement removal
=> Release Feature/banner auth link fix

core/templates/core/base.html
Fix to stop modals from showing up to anonymous users
=> Show modals to authenticated users only

CHANGELOG.md, exportplan/templates/exportplan/pdf_download.css, exportplan/templates/exportplan/pdf_download.html
CONTEXT: This changeset updates reference to fonts in CSS. Updated country name object ref in doc.
=> Update font asset path. Update country object ref

CHANGELOG.md, domestic/templates/domestic/country_guide.html
update incorrect learning banner copy
=> update incorrect learning banner copy

search/helpers.py
=> Hotfix GP2-2240: Search tuning - adjust boost of Articles to put them slightly ahead of Markets

search/helpers.py
=> GP2-2240: Search tuning - adjust boost of Articles to put them slightly ahead of markets

CHANGELOG.md, requirements.txt, requirements_test.txt
This changeset upgrade wagtail to 2.11.7 also upgrade number of package includes reportlab
=> Wagtail upgrade to 2.11.7

CHANGELOG.md, config/url_redirects.py, tests/unit/config/test_url_redirects.py
This changeset adds additional redirect from BAU to magna
=> Added url redirect for trade and ISD

README.md
=> update readme, macOs psycopg2, openssl issue

cms_extras/modeladmin.py, core/blocks.py, core/views.py, requirements.txt, requirements_test.in, requirements_test.txt, tests/unit/search/test_views.py
Unpin black in requirements_test.in, so we don't get out of step with CI.
=> Unpin black

core/templates/components/header_footer/domestic_header_nav.html
=> Home link removed from desktop header menu

CHANGELOG.md, exportplan/templates/exportplan/sections/funding-and-credit.html
=> Typo on the Funding and credit page

CHANGELOG.md, exportplan/templates/exportplan/sections/about-your-business.html
=> Disclaimer for the Beta release

CHANGELOG.md, core/templates/components/google_tag_manager_body.html, core/templates/components/header_footer/domestic_header_nav.html, domestic/templates/domestic/base.html, requirements.txt, requirements_test.txt
This changeset fixes minor niggles related to porting directory-components into great-cms
* Fixes: GA variable in noscript block
* Fixes: unquoted lang string in <IE9
* Fixes: dead code
Also:
* Updates Python dependencies to bring in Django 2.2.21 and latest SSO client version
BROKEN:
FIXED:
-------
BROKEN:
FIXED:
=> GP2-2303: Quick cleanup of niggles related to directory-components template vars

CHANGELOG.md, runtime.txt
=> Bump buildpack version

CHANGELOG.md, exportplan/templates/exportplan/sections/marketing-approach.html
=> GP2-2421 update content

CHANGELOG.md, domestic/templates/domestic/finance/trade_finance.html, domestic/templates/domestic/ukef/contact_form.html, domestic/templates/domestic/ukef/country_cover.html
Assortment of layout tweaks for migrated BAU pages.
=> GP2-2130: Layout tweaks to ukef pages

CHANGELOG.md, exportplan/templates/exportplan/dashboard_page.html
=> GP2-2396 - mobile-Logo upload issue

CHANGELOG.md, core/templates/components/header_footer/domestic_header_nav.html
=> GP2-2529: Update export plan url in signed in header

CHANGELOG.md, core/context_processors.py
=> GP2-2550-remove-forgotten-password-link 

package-lock.json, package.json
=> update dependencies to fix vulnerabiltiies

CHANGELOG.md, domestic/templates/domestic/domestic_dashboard.html
=> remove Export opportunities tab for the Dashboard

CHANGELOG.md, exportplan/core/serializers.py
=> GP2-2775-save-business-risk 

CHANGELOG.md, core/templates/components/header_footer/domestic_footer.html, core/templates/core/footer.html
=> GP2-2777: Remove footer dit logos

CHANGELOG.md, exportplan/core/serializers.py
=> GP2-2775-getting-paid-error 

CHANGELOG.md, exportplan/templates/exportplan/includes/section_data/travel-and-business-policies__data.html
=>  remove-lesson 

CHANGELOG.md, exportplan/templates/exportplan/sections/getting-paid.html, package-lock.json
=> remove Getting paid page tooltip

CHANGELOG.md, core/templatetags/video_tags.py, tests/unit/core/test_templatetags.py
=> GP2-2797: Disable video downloads

CHANGELOG.md, config/settings.py, requirements.in, requirements.txt, requirements_test.txt
=> enable-apm-logging

CHANGELOG.md, core/templates/core/404.html
+ update changelog, post-release
Wrong (my emphasis):
>  use the search box above to find the information **your** need.
Fixed:
>  use the search box above to find the information **you** need.
=> GP2-2831 - fix typo on 404 page

CHANGELOG.md, exportplan/templates/exportplan/dashboard_page.html, exportplan/templates/exportplan/includes/sidebar.html
Adds descriptive text to company logo displayed in EP sidebar.
ATM, the logo facility is disabled,. but this fix means that re-enabling it won't introduce a new accessibility error.
=> GP2-2890, GP2-2891 - DAC NonText Content 01/02

CHANGELOG.md, exportplan/templates/exportplan/dashboard_page.html
Better text for update logo link in EP.
This is not in use ATM as users cannot upload a logo.
=> GP2-2893 - DAC Link Purpose 01

exportplan/core/helpers.py, tests/unit/exportplan/test_helpers.py
=> fix-create-exportplan-error

CHANGELOG.md, search/forms.py, search/templates/search.html, search/templates/search_feedback.html, search/urls.py, search/views.py, tests/unit/search/test_forms.py, tests/unit/search/test_views.py
Mostly a lift and shift. Note that there are two paths through the feedback form - with and without details
=> GP2-2981: Port Search Feedback page from V1 into V2

CHANGELOG.md, core/templates/robots.txt, tests/unit/core/test_views.py
=>  remove-disallow-sso-robots.txt 

CHANGELOG.md, core/templates/core/base.html
- Added -great.gov.uk as default to django template.
- Checked locally and seems like all titles have been updated. The rest is edited via Wagtail-CMS like contact-us, services etc. example below with HAHAHA
Before:
After:
=> GP2-3120-Append-great-gov-uk

CHANGELOG.md, sso_profile/templates/personal_profile/personal-profile-edit-form.html
BUGFix: adding missing csrf token
Go to the personal profile section of the account area and edit details.
=> GP2-3208 - Fix error while updating personal profile

core/components/package-lock.json, core/components/package.json, package-lock.json, package.json
=> Gp2 3164 - vulnerability

CHANGELOG.md, domestic/templates/domestic/base.html
to be tested by Performance Analyst via Bing search console.
=> adding bing search console meta tag

CHANGELOG.md, sso_profile/templates/business_profile/disconnect-from-company.html
=> GP2-3372-add-crsf-token-admin-disconnect

requirements.txt, requirements_test.txt
=> fix-permissions

core/components/package-lock.json, domestic/package-lock.json
=> - Vulns 24th September.

CHANGELOG.md, contact/urls.py
=>  hotfix-SOO-contact-issue

CHANGELOG.md, contact/templates/domestic/contact/office-finder.html
=>  GP2-3446-change-london-ita-search

CHANGELOG.md, domestic/templates/domestic/base.html
=> add bing search console, increase priority in head tag

.gitignore, .pii-ner-exclude, .pre-commit-config.yaml, CHANGELOG.md
CONTEXT: This changeset introduces PII (Personal Identifiable Information) and secret check hooks for pre-commit as per DIT's [pii-secret-check-hooks](https://github.com/uktrade/pii-secret-check-hooks)
=> PII and secret check hooks for pre-commit

.pre-commit-config.yaml
=> Exclude file for PII checks

config/settings.py, contact/models.py, core/cms_panels.py, domestic/cms_panels.py, domestic/models.py, domestic/templates/domestic/base.html, pii-secret-exclude.txt
=> Added configuration and removed old SEO fields

CHANGELOG.md, pii-secret-exclude.txt, sso/helpers.py, sso_profile/enrolment/helpers.py, sso_profile/enrolment/mixins.py, sso_profile/enrolment/views.py, tests/unit/sso_profile/enrolment/test_helpers.py, tests/unit/sso_profile/enrolment/test_views.py
CONTEXT: This changeset fixes the notification flow on enrolment when a verification code is requested to be re-sent.
=> [GP2-3381] verification code enhancements

contact/templates/domestic/contact/office-finder.html, core/templates/core/compare_countries.html, core/templates/core/login.html, core/templates/core/signup.html, domestic/templates/domestic/marketaccess/report_a_barrier.html, domestic/templates/domestic/ukef/contact_form.html, domestic/templates/domestic/ukef/country_cover.html, domestic/templates/domestic/ukef/how_we_assess.html, domestic/templates/domestic/ukef/project_finance.html, domestic/templates/domestic/ukef/what_we_offer.html, exportplan/templates/exportplan/dashboard_page.html, exportplan/templates/exportplan/sections/about-your-business.html, exportplan/templates/exportplan/sections/adapting-your-product.html, exportplan/templates/exportplan/sections/business-objectives.html, exportplan/templates/exportplan/sections/business-risk.html, exportplan/templates/exportplan/sections/costs-and-pricing.html, exportplan/templates/exportplan/sections/funding-and-credit.html, exportplan/templates/exportplan/sections/getting-paid.html, exportplan/templates/exportplan/sections/marketing-approach.html, exportplan/templates/exportplan/sections/target-markets-research.html, exportplan/templates/exportplan/sections/travel-plan.html, exportplan/templates/exportplan/start.html, learn/templates/learn/automated_list_page.html, learn/templates/learn/landing_page.html, pii-secret-exclude.txt, sso_profile/package-lock.json, sso_profile/templates/business_profile/business-profile-member.html, sso_profile/templates/business_profile/is-not-business-profile-user.html, sso_profile/templates/business_profile/profile.html
This changeset adds meta description for various pages
=> Added meta description for various pages

CHANGELOG.md, requirements.txt, requirements_test.txt
=> Updated requirements

CHANGELOG.md, regex.py, sso/serializers.py
Ease the validation on telephone numbers in sign-up to allow brackets, hyphens, multiple plusses and leading brackets.
=> GP2-3859 - Telephone number validation relaxing

CHANGELOG.md, contact/urls.py
=> Route logged-out SOO calls to magna login

CHANGELOG.md, exportplan/context.py
=> GP2-3906-fix-pdf-worldbank-data

sso_profile/common/sass/profile.scss, sso_profile/templates/enrolment/base.html, sso_profile/templates/enrolment/wizard.html
=> Fix missing enrolment styles

core/templates/components/statistics_card_grid.html
Adds recent changes back to statistics card markup.
=> Fix bad merge by re-adding markup changes

CHANGELOG.md, config/settings.py, development.yml, requirements.in, requirements.txt
This changeset migrate code from elastic search to OpenSearch.
- [] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)
=> Switching to opensearch from elasticsearch

core/templates/core/includes/bar_chart.html, domestic/models.py, domestic/templates/domestic/country_guide.html, tests/unit/domestic/test_models.py
Move feature switch to model so it can be covered by test.
Slight refactor of markup with extraction of bar chart into separate template for reusability.
=> GLS-180 move feature switch

CHANGELOG.md, contact/templates/domestic/contact/office-finder.html
=> Fixed duplicate header of office finder

CHANGELOG.md, domestic/static/cms-admin/js/select2/select2.js, pii-secret-exclude.txt
=> Fix select2 vulnerability

CHANGELOG.md, core/templates/core/includes/data_source.html
=> Replace Next release with Last release for market guides date sources

README.md
=> Change versioning strategy in README to SemVer from CalVer

CHANGELOG.md
=> 2.11.0 post-release CHANGELOG update

CHANGELOG.md, config/settings.py
=> Configure csrftoken cookie to be HttpOnly

CHANGELOG.md
Post-release changelog update for release 2.12.0.
=> Post-release changelog update - 2.12.0

CHANGELOG.md
=> Update changelog for release 2.13.0

core/templates/core/includes/_article_video.html
This changeset adds a transcript to the video on the article/campaign page. This is second PR for this ticket after feedback from Neil
=> Added transcript link to video

CHANGELOG.md
This PR updates the changelog following release 2.15.0.
=> Post-release changelog update - 2.15.0

CHANGELOG.md
Post-release changelog following release 2.16.0
=> Update changelog post release 2.16.0

CHANGELOG.md, domestic/templates/domestic/landing_page.html
if else statement on hero cta wasn't functioning, so solved this.
Tick or delete as appropriate:
Workflow
[ x] Ticket exists in Jira https://uktrade.atlassian.net/jira/software/projects/GGR/boards/357?selectedIssue=GGR-2
[ x] Jira ticket has the correct status.
[ x] [Changelog](https://github.com/uktrade/great-cms/pull/CHANGELOG.md) entry added.
Reviewing help
[x ] check on safari 601px to 900px
[x ] 
Housekeeping
[ x] Added all new environment variables to Vault.
[x ] Cleaned up old feature flags
[ x] Upgraded any vulnerable dependencies.
[x ] Ran the make manage download_geolocation_data command
[ x] I have updated security dependencies
[x ] Python requirements have been re-compiled.
[x ] Frontend assets have been re-compiled.
=> hero cta text fix on signed in

requirements.in, requirements.txt, requirements_test.txt
=> KLS-117 oauthlib vulnerability

CHANGELOG.md, package-lock.json
=> Update minimatch 3.0.4 -> 3.1.2

CHANGELOG.md
This PR merges the release branch into the develop branch to fix merge conflicts when merging develop into release.
=> Merge release develop

CHANGELOG.md, sso/api.py, sso/serializers.py, tests/unit/sso/test_helpers.py
This PR enables input string sanitisation via serialiser on the product selector form.
=> Add serializer validation to product selector form

.pre-commit-config.yaml, CHANGELOG.md, config/settings.py, core/blocks.py, core/constants.py, domestic/models.py, requirements.in, requirements.txt, requirements_test.in, requirements_test.txt, tests/unit/activitystream/test_serializers.py, tests/unit/contact/test_views.py, tests/unit/core/test_models.py, tests/unit/search/test_helpers.py, tests/unit/sso/test_models.py
=> KLS-282 Great-cms django to version 3.2.16

.pre-commit-config.yaml, CHANGELOG.md, config/settings.py, core/blocks.py, core/constants.py, domestic/models.py, requirements.in, requirements.txt, requirements_test.in, requirements_test.txt, tests/unit/activitystream/test_serializers.py, tests/unit/contact/test_views.py, tests/unit/core/test_models.py, tests/unit/search/test_helpers.py, tests/unit/sso/test_models.py
=> Staging release

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> KLS-395 Update django to 3.2.18, directory-sso-api-client to >= 7.1.1

CHANGELOG.md
=> Update changelog with release tag post deploy to production

CHANGELOG.md
=> Update changelog for version 2.27.0

CHANGELOG.md, core/templates/microsites/includes/microsite_detail_content.html
Layout tweak for article header
=> KLS-367: heading, strapline, last published layout

core/templates/microsites/blocks/cta.html
=> KLS-474: fix cta block

core/models.py, export_academy/templates/export_academy/registration_form_success.html, export_academy/urls.py
Rename EA path upcoming-events to events
=> Rename EA path upcoming-events to events

export_academy/filters.py, export_academy/managers.py
=> Hide draft events from listings

international_online_offer/forms.py, international_online_offer/templates/ioo/contact.html, tests/unit/international_online_offer/test_forms.py
Needed full list of countries to select from on EYB contact form. Using directory constants list
=> Added directory constants countries list to EYB contact form

domestic/templates/domestic/includes/article_detail_content.html
=> Hotfix backport to CSS bullet points missing

domestic/templates/domestic/includes/streamfield.html
=> Fixed article page/streamfield block

international_online_offer/templates/ioo/edit_your_answers.html
EYB: Feedback updates to summary page
=> EYB: Feedback updates to summary page

export_academy/filters.py, export_academy/helpers.py, export_academy/templates/export_academy/event_list.html, export_academy/templatetags/event_list_buttons.py, export_academy/views.py, pii-secret-exclude.txt, tests/unit/export_academy/test_helpers.py
Refactor the event's booking period filter for a particular user by renaming the query parameter key and removing its value from the session.
=> Refactor user-related event filter

requirements.in, requirements.txt, requirements_test.txt
This PR removes the Pisa library as it no longer exists.
=> Remove pisa from requirements

requirements.txt, requirements_test.txt
Bump version of great-components to 2.1.3
=> bump great-components to 2.1.3

export_academy/templates/modeladmin/export_academy/create.html, export_academy/templates/modeladmin/export_academy/edit.html
removed unneeded template _editor_css.html
=> removed unneeded template _editor_css.html

sso/views.py
Fix logout missing serialiser error
=> Fix missing serializer issue

config/utils.py, tests/unit/config/test_utils.py
Update config to allow UAT to pull pages from dev and staging environments.
=> Wagtail transfer configuration update 

config/settings.py, requirements.in, requirements_test.txt
Small patch to unblock the pipeline on Jenkins
=> update STATICFILE_STORAGE environment string

international_online_offer/templates/ioo/base.html
Script tags adding into EYB base head_js and body_js for use tracking user journeys
=> Google Analytics script tags added for EYB

activitystream/serializers.py, activitystream/urls.py, activitystream/views.py, pii-secret-exclude.txt, tests/unit/activitystream/test_serializers.py, tests/unit/activitystream/test_views.py
Work to allow activity stream to parse objects for EYB in its expected format and send to data-flow for use in data workspace
=> Feature/ioo 516 - EYB user and triage data to activity stream

activitystream/views.py
Fix to get ID the correct way for EYB activity stream views
=> Fix for id getter on acitivity stream view for EYB

activitystream/views.py
EYB Activity stream datetime in build after for view
=> Adding datetime to build after

core/templates/microsites/blocks/columns.html
This PR is to remove a bug in the language persistence in microsite's.
=> removed filter from column.html

activitystream/filters.py, activitystream/pagination.py, activitystream/serializers.py, activitystream/urls.py, activitystream/views.py, tests/unit/activitystream/test_serializers.py, tests/unit/activitystream/test_views.py
Big refactor of the Activity Stream views which abstracts filtering and pagination and makes everything much cleaner.
=> Refactor Activity Stream views

requirements.txt, requirements_test.txt
=> Recompile requirements

export_academy/filters.py
Fix past events listing issue in EA
=> KLS-783 Fix past events listing issue in EA

export_academy/templates/export_academy/includes/event_action_buttons.html
https://uktrade.atlassian.net/jira/software/projects/EAM/boards/376/backlog?assignee=63343adf88ed2ebef97c64ac&selectedIssue=EAM-356
=> Add hidden text to export academy register button for screen readers

export_academy/templates/export_academy/includes/event_action_buttons.html, international_online_offer/forms.py, international_online_offer/templates/ioo/edit_your_answers.html, international_online_offer/templates/ioo/guide.html, international_online_offer/templates/ioo/triage/intent.html, international_online_offer/views.py, tests/unit/international_online_offer/test_views.py
=> Production release

international_online_offer/core/scorecard.py, international_online_offer/templates/ioo/trade.html, tests/unit/international_online_offer/test_scorecard.py
Scorecard changes, removal of levelling up and changes to figures
n/a
=> Scorecard changes, removal of levelling up and changes to figures

export_academy/helpers.py, export_academy/views.py, tests/unit/export_academy/test_helpers.py
guard against no sector selected in EA registration confirm page
No Ticket
=> guard against no sector selected in EA registration confirm page

contact/mixins.py, contact/views.py
Submits the DPE Contact form feedback to zendesk.
=> DPE-198: submit feedback form

package-lock.json, package.json
This PR updates our version of ES-lint and it's plugins so as to use a secure version of the `word-wrap` package.
=> KLS-825 - Update eslint and optionator versions

international_online_offer/core/constants.py, international_online_offer/templates/ioo/guide.html, international_online_offer/templates/ioo/includes/profile_form.html, international_online_offer/templates/ioo/index.html, international_online_offer/templates/ioo/signup.html, international_online_offer/templates/ioo/trade.html
Microcopy changes based on user research. Only text changes with some conditional statements to hide / show content
N/A
=> Added micro copy changes based on UR

export_academy/templates/export_academy/includes/event_action_buttons.html
Event recording duration text change
=> Event recording duration text

config/settings.py, domestic/views/campaign.py
Needed to filter by url path rather than slug as slug is not unique
https://uktrade.atlassian.net/jira/software/projects/KLS/boards/359?assignee=63343adf88ed2ebef97c64ac&isInsightsOpen=true&selectedIssue=KLS-955
=> Fix duplicate languages in language selector

international_online_offer/templates/ioo/edit_your_answers.html
=> Typo on edit answers page

international_online_offer/templates/ioo/guide.html, international_online_offer/templates/ioo/index.html
Content / text changes based on stakeholder feedback for content team
=> Content updates based on stakeholder feedback

core/templatetags/content_tags.py
https://uktrade.atlassian.net/jira/software/projects/KLS/boards/359?assignee=63343adf88ed2ebef97c64ac&isInsightsOpen=true&selectedIssue=KLS-956
=> Fix video stacking in richtext field in microsites

activitystream/serializers.py, core/models.py, core/templatetags/content_tags.py, core/views.py, core/wagtail_hooks.py, tests/conftest.py, tests/unit/core/test_models.py
This ticket resolves Flake8 6.1.0 errors showing on great-cms.
=> UPDATED Flake8 6.1.0 incompatibilities.

core/constants.py, core/templates/core/get_export_help_experiment_results.html
This PR makes two small text changes to the get export help experiment form and results.
=> Text updates for experiment forms

core/templates/core/header.html
Adds "Support" link to header behind Digital Entry point feature flag
=> KLS-963: Add support link to header

core/templates/components/pagination/pagination.html, export_academy/views.py, tests/unit/domestic/test_templatetags.py
Change pagination on export academy events to use latest GDS (without ellipis for now)
N/A
=> Quick fix for pagination

international_online_offer/context_processors.py, international_online_offer/core/constants.py, international_online_offer/core/helpers.py, international_online_offer/models.py, international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/header.html, international_online_offer/urls.py, international_online_offer/views.py, tests/unit/international_online_offer/test_helpers.py, tests/unit/international_online_offer/test_models.py, tests/unit/international_online_offer/test_views.py
More tidy up, updates and general improvements to EYB. 
N/A
=> Tidying up

international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/includes/rent.html, international_online_offer/templates/eyb/includes/salary.html, international_online_offer/templates/eyb/index.html
Minor text / content updates across the site. 
N/A
=> Content updates

contact/forms.py, contact/templates/domestic/contact/export-support/cya.html, contact/templates/domestic/contact/export-support/includes/topic-landing-card.html, core/static/javascript/digital-entry-point.js
Tracks users journey though triage process and passes journey value to a hidden field as part of contact form submission data.
=> KLS-1065: collect triage journey data

international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/trade_associations.html, international_online_offer/templates/eyb/trade_shows.html
Copy changes to trade events / associations and link to personalised guide bottom of step by step guide
N/A
=> Copy changes to trade events / associations and link to personalised

export_academy/templates/export_academy/event_list.html, export_academy/views.py, tests/unit/export_academy/test_views.py
Hotfix to undo the changes to UKEA events listings
=> KLS-1045 hotfix

contact/templates/domestic/contact/export-support/includes/topic-landing-card.html, core/templatetags/content_tags.py, tests/unit/core/test_templatetags.py
Minor change to how external/internal links icons work
=> KLS-1145: change links to full urls

international_online_offer/templates/eyb/guide.html
Simple text change on guide where there is a link to the personalised guide.
N/A
=> Content change for link to personalised guide

contact/forms.py, contact/helpers.py, contact/templates/domestic/contact/export-support/cya.html, contact/views.py
Various small content tweaks for DEP contact form.
=> DPE-488: Content amends for contact form

contact/templates/domestic/contact/export-support/get-in-touch.html, contact/templates/domestic/contact/export-support/includes/get-in-touch.html, contact/templates/domestic/contact/export-support/topic-landing.html, core/cms_slugs.py, core/static/javascript/digital-entry-point.js, core/templates/components/header_footer/footer_base.html, core/templates/core/footer.html
Adds link in footer to DEP triage and various small content changes
=> KLS-1140: more dep content changes and footer link

core/templates/components/digital_entry_point_homepage_row.html, domestic/templates/domestic/landing_page.html
Adds custom GA tracking to new DEP homepage tiles
=> DPE-476: adds custom ga tracking to dep homepage tiles

config/url_redirects.py, contact/templates/domestic/contact/export-support/get-in-touch.html, domestic/urls.py, tests/unit/config/test_url_redirects.py
Removes trade barrier page redirects.
=> DPE-506: Remove trade barrier redirects

contact/templates/domestic/contact/export-support/support.html, core/templates/components/card.html
=> DPE-465: Fixes pixelated hero image

activitystream/serializers.py, tests/unit/activitystream/test_serializers.py
This PR refactors the microsite serializer, and updates the url field so that the correct url for microsites is returned.
=> Update microsite serialiser to fix URL field

contact/helpers.py
Fixes issue with dep contact form due to incorrect form field name
=> DPE-488: fixes bug in contact due to incorrect field value

contact/templates/domestic/contact/export-support/get-in-touch.html, contact/templates/domestic/contact/export-support/includes/get-in-touch.html
=> DPE-471: Update contact copy

export_academy/templates/export_academy/includes/event_duration.html
Make duration spacing consistent between different event states
=> KLS-1228: event duration spacing

activitystream/filters.py, activitystream/pagination.py, activitystream/views.py
=> Fix pagination on CMS content dataset

international_online_offer/forms.py, international_online_offer/templates/eyb/404.html, international_online_offer/templates/eyb/csat_feedback.html, international_online_offer/templates/eyb/feedback.html, international_online_offer/views.py, tests/unit/international_online_offer/test_views.py
Change feedback form to basic one and keep csat form for future dev
N/A
=> Change feedback form to basic one and keep csat form for future dev

config/settings.py, core/middleware.py, pii-secret-exclude.txt, requirements.in, requirements.txt, requirements_test.txt, tests/unit/core/test_middleware.py
Reverts uktrade/great-cms#2636
=> Revert "Add middleware to limit data on the domain and CSP via HTTP headers"

core/models.py
Make sure to prefix media only once
=> Fix media edit bug

package-lock.json, package.json
=> KLS-1341: bump postcss

package-lock.json, package.json
=> KLS-1453: patch babel/traverse

manifest.yml
cflinux4fs upgrade: This change will fix the version of cflinuxfs4
=> KLS-1445 add stack cflinuxfs4 reference in manifest.yml

contact/templates/domestic/contact/export-support/cya.html
Adds missing privacy policy url to link
=> DPE-638: add missing privacy policy link

contact/helpers.py, contact/views.py, tests/unit/contact/test_helpers.py, tests/unit/contact/test_views.py
Small extension of [this PR](https://github.com/uktrade/great-cms/pull/2707) with some refactoring and introduction of sector -> tag mapping.
=> KLS-1450 zendesk tagging automation

core/templates/components/cookie_notice.html
=> added great class

international_online_offer/forms.py, international_online_offer/templates/eyb/contact.html, international_online_offer/templates/eyb/edit_your_answers.html, international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/header.html, international_online_offer/templates/eyb/includes/contact_success.html, international_online_offer/views.py
Added new success component for contact us page 
N/A
=> Contact us form content update

core/templates/core/header.html
Fixes issue with cookie modal not closing when logged in
=> KLS-1572: fixes cookie modal bug

international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/includes/step_guide.html
Added new content and structure to EYB step by step guide
N/A
=> Added new content and structure to EYB step by step guide

config/url_redirects.py
(https://uktrade.atlassian.net/jira/software/projects/KLS/boards/359?assignee=63343adf88ed2ebef97c64ac&isInsightsOpen=true&selectedIssue=KLS-1580)
=> Redirect VCA to international link

international_online_offer/core/helpers.py, international_online_offer/templates/eyb/includes/rent.html, international_online_offer/templates/eyb/includes/step_guide.html
Updated trade association mappings to show for medical devices sector and content changes on step by step guide
N/A
=> Updated trade association mappings to show for medical devices sector and content changes

config/url_redirects.py
Change the url redirect to vcu
=> KLS-1607 fix vcu url redirect

contact/templates/domestic/contact/export-support/cya.html
Updates privacy policy link for DEP contact form
=> KLS-1644: update privacy policy link

domestic/views/campaign.py
=> Fix current locale microsites error

learn/templates/learn/detail_page.html, tests/unit/core/test_wagtail_hooks.py, tests/unit/domestic/views/test_views.py
=> Put bread crumb back in detail page (rebase merge error)

config/url_redirects.py, domestic/urls.py, tests/unit/domestic/test_urls.py, tests/unit/domestic/views/test_views.py
Updating the ticket https://uktrade.atlassian.net/browse/KLS-1597 and move it behind a feature flag .
=> KLS-1655: Update the redirect to be behind a feature flag

learn/templates/learn/detail_page.html
Put promo back on LTE article page
=> KLS-1594: reinstate promo of article page

core/models.py
Small PR to change the label on StreamBlock table fields to 'Data table'
=> Alter streamblock lable to 'Data table'

core/templates/core/curated_topic.html, learn/templates/learn/automated_list_page.html
Updates card styling for LTE pages
=> KLS-1652: Update cards for LTE

core/urls.py
=> different endings for BASE_URL in different ENVs

core/models.py
Small PR to add an SEO panel to LTE parent and child pages.
=> add seo panel to LTE pages

domestic/templates/domestic/country_guide.html
=> fix country guide read more link

core/templatetags/content_tags.py, tests/unit/core/test_templatetags.py
Remove slash at end of link image url if it is present
=> remove slash at end of link image url if it is present

config/settings.py
=> KLS-1682 CSP (Content Security Policy) warnings in production

core/templates/components/great/share.html
Encode field values for share component
=> KLS-1767: encoded field values

international_online_offer/templates/eyb/footer.html, international_online_offer/templates/eyb/includes/dbt_banner.html
Adding copyright text into EYB footer
N/A
=> Adding copyright text into EYB footer

international_online_offer/models.py, international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/index.html, international_online_offer/urls.py, international_online_offer/views.py, tests/unit/international_online_offer/test_views.py
Change to revert some of EYB workflow updates
N/A
=> Change to revert some of EYB workflow updates

pii-secret-exclude.txt
=> Update GeoIp2 data

international_online_offer/core/scorecard.py, tests/unit/international_online_offer/test_scorecard.py
EYB: Adding new hpo scoring metrics for healthcare services sector
N/A
=> Adding new hpo scoring for healthcare services sector

sso_profile/templates/enrolment/companies-house-success.html
=> missed breadcrumb change

core/templates/core/product-market.html
=> Close H1 in product-market template

export_academy/models.py, export_academy/tasks.py
CONTEXT: This PR updates the UKEA email notification process by delegating the mailout task to a background job handled by Celery.
=> Send UKEA email notifications via background jobs

contact/templates/domestic/contact/export-support/base.html, contact/templates/domestic/contact/export-support/step-5.html
Fixes inline feedback form fields appearing in markets list
=> KLS-1939: Fix inline feedback fields appearing in market options

export_academy/templates/export_academy/event_video.html
missed passing in event.name to render_video tag in one place
=> missed passing in event.name to render_video tag in one place

international_online_offer/context_processors.py
Removal of looping next url for feedback and contact form.
N/A
=> Removal of looping next url

contact/forms.py
Fixes production bug with telephone numbers with whitespace causing forms to not send
=> DPE-705: Remove whitespace from telephone number

contact/forms.py, regex.py
=> UAT and production release

international/templates/international/header.html
PR to add data-location and data-title attributes to EYB sub nav to assist with tracking user journeys.
=> IOO-1175 - add data-location, data-title to EYB subnav

core/templates/core/curated_topic.html
=> DEA-280 : Add id to the heading to be used as an anchor

contact/forms.py, contact/templates/domestic/contact/export-support/step-6.html, tests/unit/contact/test_forms.py, tests/unit/contact/test_views.py
Add a new select field for page 6 of the contact form
On ticket
=> Additional dropdown on form

contact/templates/domestic/contact/export-support/get-in-touch.html, contact/templates/domestic/contact/export-support/includes/get-in-touch.html, contact/views.py, core/templates/components/landing_hero_with_input.html
Update the homepage banner subheading, the content on the DEP support forms, and the step 1 form heading
Screenshots on tickets
=> Updated content for homepage subheading and SDC form

core/cms_slugs.py, core/static/javascript/digital-entry-point.js, core/templates/components/header_footer/footer_base.html, core/templates/core/footer.html, domestic/templates/domestic/country_guide.html
Updates DEP landing page url references
=> DPE-735: Update dep landing page url

core/templates/core/header.html
Added ID's to the main navigation auth links to assit with auto testing
=> Added ID's to main sign in and sign out navigation links

international/templates/international/footer.html
Accessibility link added to international footer and updated contact us link text to help using this site
N/A
=> Accessibility link added to international footer and updated contact us link text to help using this site

international/templates/international/footer.html
=> Release PR

core/templates/core/header.html, requirements.in, requirements.txt, requirements_test.in, requirements_test.txt
Added ID to main menu link to help with auto testing and bumped Django & Black
=> Greatuk 107 add id to menu link

export_academy/templates/export_academy/accounts/signin.html, export_academy/templates/export_academy/accounts/signup.html, export_academy/templates/export_academy/course_page.html, export_academy/templates/export_academy/event_on_demand_video.html, export_academy/templates/export_academy/includes/event_action_buttons.html
New class to help test suite find signin linkes throughout ukea
=> Added new class to ukea signin links to help test suite

domestic/templates/domestic/performance_dashboard_page.html
Update the working on the performance dashboard banner
=> GREATUK-597: Update performance dashboard banner wording

requirements.in, requirements.txt, requirements_test.txt
=> Bump gunicorn to 22.0.0

export_academy/templates/export_academy/landing_page.html
UK Export academy cards refactored to use the new great design system cards.
=> Greatuk 431 ukea cards visual defects

.circleci/config.yml
Bump redis in CircleCi to 7.2.4
=> Bump redis in CircleCi to 7.2.4

core/templates/components/header_footer/footer_base.html, core/templates/core/footer.html
=> Fix cookies link path in footer

domestic/templates/domestic/cookie-preferences.html
=> Update path for cookies policy page link

international/templates/international/base.html, international/templates/international/index.html
New canonical added to international base and index
=> New canonical tag added to internatiton pages

core/static/javascript/great.task-validation.js
Minor tweaks to task validation modal
=> ET-103: task validation modal tweaks

contact/templates/domestic/contact/export-support/topic-landing.html, core/static/javascript/great.task-validation.js
Small copy updates to task validation modal
=> ET-103: copy updates

international_online_offer/forms.py
Update copy on EYB company location drop-down.
=> IOO-1362 update copy on eyb profile

core/templates/components/great/card.html
Fixes bug with dep journey tracking
=> ET-127: Fix undefined title issue

activitystream/serializers.py, activitystream/urls.py, activitystream/views.py
Expose endpoint for activity stream for UKEA CSATS
=> GRTLV-70: Activity stream changes for UKEA csat

core/pingdom/services.py, core/urls.py, core/views.py, requirements.in, requirements.txt, requirements_test.txt, tests/unit/core/test_views.py
Add health check for dbt platform
=> Add health check for dbt platform

activitystream/serializers.py
Quick fix for AS video on demand tracking issue - not solution
=> Quick fix for AS video on demand tracking issue - not solution

domestic/models.py, domestic/templates/domestic/country_guide.html, tests/unit/domestic/test_models.py
Add sector spotlight CTA to Germany market guide
=> ET-129 add sector spotlight cta for Germany

international_online_offer/forms.py
Fixes a small bug whereby the company location defaulted to Abu Dhabi when the EYB Profile form was submitted with no location entered.
=> EYB-11 - PATCH/bugfix on company location

international_investment/views.py
Check for investment agent email env var and escape email send if not present
N/A
=> Check for investment agent email env var and escape email send if not present

international/templates/international/404.html, international/templates/international/base.html, international/templates/international/index.html, international_investment/templates/investment/index.html, international_investment/templates/investment/investment_contact.html, international_investment/templates/investment/investment_estimate.html, international_investment/templates/investment/investment_fund.html, international_investment/templates/investment/investment_success.html, international_investment/templates/investment/investment_types.html, international_online_offer/templates/eyb/article.html, international_online_offer/templates/eyb/bci.html, international_online_offer/templates/eyb/edit_your_answers.html, international_online_offer/templates/eyb/guide.html, international_online_offer/templates/eyb/index.html, international_online_offer/templates/eyb/login.html, international_online_offer/templates/eyb/profile.html, international_online_offer/templates/eyb/signup.html, international_online_offer/templates/eyb/trade_associations.html, international_online_offer/templates/eyb/trade_shows.html, international_online_offer/templates/eyb/triage/hiring.html, international_online_offer/templates/eyb/triage/intent.html, international_online_offer/templates/eyb/triage/location.html, international_online_offer/templates/eyb/triage/sector.html, international_online_offer/templates/eyb/triage/spend.html
New meta description added for all services under international
N/A
=> New meta description added for all services under international

domestic/templates/domestic/ukef/how_we_assess.html
=> Fixed typo is image name

config/env.py, pii-secret-exclude.txt, requirements.in, requirements.txt, requirements_test.txt, tests/unit/config/test_env.py
CONTEXT: This PR adds a proof of concept for an environment reader that is backward compatible so that the app can access config data regardless of the platform is deployed to.
=> Platform environment reader POC

international/templates/international/footer.html, international/templates/international/header.html
Add aria label to great logo in International header and footer.
=> EYB-49 add aria label to great logo in header and footer

international_investment/forms.py, international_investment/templates/investment/index.html
Error message updated for investment other and typo fix on investment home
N/A
=> Error message updated for investment other and typo fix on investment home

international_online_offer/models.py, international_online_offer/services.py, international_online_offer/templates/eyb/includes/salary.html, international_online_offer/templates/eyb/includes/salary_v2.html, requirements.in, requirements.txt, requirements_test.txt, tests/unit/international_online_offer/test_services.py
This PR refines the messaging when no salary data is available by informing the user if data is unavailable for the entire sector or just for that sector/geographic region combination.
=> EYB-170 - refine error feedback on EYB salary component

requirements.in, requirements.txt, requirements_test.txt
Bump urllib3, certifi and djangorestframework
=> Bump urllib3, certifi and djangorestframework

requirements.in, requirements.txt, requirements_test.txt
Fixed XSS vulnerability in DRF by upgrading package.
=> UPGRADED DRF package.

contact/templates/domestic/contact/export-support/base.html, contact/templates/domestic/contact/export-support/feedback-confirmation.html, contact/templates/domestic/contact/export-support/topic-landing.html, tests/unit/contact/test_views.py
Remove "noindex" meta tag from dep pages
=> ET-259: Make all dep pages indexable except get in touch

core/templates/core/login.html, core/templates/core/page_blank.html, core/templates/core/signup.html
Small PR to change block names in the login and signup templates.
=> fixed incorrect use of block names

core/models.py
=> Added new hint to media file field

core/utils.py
dont prepend www. if host already has it
=> dont prepend www. if it already has it

core/utils.py
=> fix prepend of www

Procfile, manifest.yml
=> Added new build pack to gain access to npm in envs

.cfignore
=> removed package.json from cfignore

package.json
=> bump node and npm

international/templates/international/base.html, international/templates/international/index.html
Add back international canonical ur
=> Add back international canonical url

contact/views.py
Implements potential fix to prevent spam/bot submission to inline feedback from
=> ET-302: Prevent bot inline form submissions

contact/templates/domestic/contact/export-support/includes/topic-landing-card.html
Applies dep card accessible focus state to all cards on dep
=> ET-310: Apply accessible focus to all dep cards

domestic/views/ukef.py
=> fixed typo

international_online_offer/templates/eyb/includes/rent.html
=> fix deleted template tag

contact/forms.py, contact/helpers.py
Fixes typos for zendesk tagging
=> ET-349: Fixes for zendesk tagging

contact/templates/domestic/contact/export-support/includes/goods-widget.html, contact/templates/domestic/contact/export-support/includes/service-widget.html, contact/templates/domestic/contact/export-support/task-based-sub-category-page.html
Adds hardcoded goods and service widgets
=> ET-343: Goods and service widgets

international_online_offer/core/region_sector_helpers.py, international_online_offer/forms.py, international_online_offer/templates/eyb/edit_your_answers.html, international_online_offer/templates/eyb/triage/business_details.html
Iguk 319 sector lookup allow parent sectors
N/A
=> Iguk 319 sector lookup allow parent sectors

contact/templates/domestic/contact/export-support/guided-journey/step-1.html, contact/templates/domestic/contact/export-support/guided-journey/step-2.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, core/forms.py, core/mixins.py, core/urls.py, core/views.py
Adds scaffolding for product and market steps
=> ET-344: search good or service step

core/mixins.py
=> ET-344: fix form data bug

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/task-based-sub-category-page.html, core/forms.py, core/urls.py, core/views.py
=> ET-346: subject for enquiry step

core/helpers.py
Fix local download of GeoIP files
=> Fix local download of GeoIP files

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/widgets.py, core/forms.py, core/templates/components/great/filtered-radios.html, core/views.py
Initial working solution for subject of enquiry selector step
=> ET-369: subject of enquiry selector

international/templates/international/base.html
Setting privacy cookie domain as was blank
N/A
=> Setting privacy cookie domain as was blank

international/templates/international/header.html
Url fix for buy from UK international
N/A
=> Url fix for buy from UK international

contact/templates/domestic/contact/export-support/task-based-sub-category-page.html
Adds custom GA tracking to task items
=> ET-382: Add datalayer tracking for task items

contact/templates/domestic/contact/routing/step-great-account.html, core/templates/core/includes/seo_meta.html, core/templates/core/page_blank.html, core/templates/microsites/base.html, domestic/templates/domestic/article_page.html, domestic/templates/domestic/base.html, international/templates/international/base.html
=> fix x-default link

contact/templates/domestic/contact/export-support/task-based-category-page.html, core/static/javascript/great.digital-self-serve.js
GA tagging for unguided journey
=> ET-407: Unguided journey tagging

contact/templates/domestic/contact/export-support/task-based-sub-category-page.html, core/static/javascript/great.digital-self-serve.js
Adds additional datalayrer tagging to unguided journey
=> ET-407: Unguided datalayer tagging

core/fixtures/sectors.csv, core/management/commands/import_sector_tags.py, core/wagtail_hooks.py, export_academy/filters.py
Updates sector tag viewset to allow management of slugs, updates ukea filters to show slug in url instead of tag ID, and fixes import script to work with csv directly from workspace
=> update sector tag viewset

exportplan/templates/exportplan/index.html
I have added an ID to a CTA in Make an export plan. The new id will help with auto tests.
=> new element ID to help with auto tests

contact/templates/domestic/contact/export-support/includes/contact-us-promo.html, contact/templates/domestic/contact/export-support/includes/get-in-touch.html
Another minor change to some links
=> Update contact us link

config/url_redirects.py, contact/templates/domestic/contact/export-support/support.html, contact/templates/domestic/contact/export-support/task-based-category-page.html, contact/templates/domestic/contact/export-support/task-based-sub-category-page.html
Add 301 redirect for /support
Remove noindex meta tags
Update page title for support landing page
=> ET-449: Unguided journey SEO enhancements

domestic/templates/domestic/performance_dashboard_page.html, search/templates/search.html
=> ET-451: Temporary fix to css error in header issue

contact/templates/domestic/contact/export-support/guided-journey/step-1.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, contact/templates/domestic/contact/export-support/guided-journey/step-4.html, core/fixtures/sectors-and-sic-sectors.json, core/forms.py, core/views.py
Adds goods or sector functionality
Adds additional sub category pages
=> ET-461: Guided mvp additional features

international/templates/international/index.html, international_investment_support_directory/views.py
Back link broken as trying to resolve path which does not exist.
=> IGUK-414 bug fix on find a specialist url

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, core/views.py
Adds related market functionality to mvp guided journey
=> ET-461: unguided mvp - show related markets

contact/templates/domestic/contact/export-support/guided-journey/step-1.html, contact/templates/domestic/contact/export-support/guided-journey/step-2.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/goods-widget.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/includes/service-widget.html, contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html, core/forms.py, core/views.py
Further updates the guided journey mvp
=> ET-461: guided mvp goods/sector happy paths

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/exopps-widget.html
=> ET-461: unguided journey mvp - exopps promo

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/duties-and-taxes-widget.html, contact/templates/domestic/contact/export-support/includes/market-promo-widget.html, contact/templates/domestic/contact/export-support/includes/sector-promo-widget.html, contact/templates/domestic/contact/export-support/includes/trade-barriers-widget.html, contact/templates/domestic/contact/export-support/includes/ukea-widget.html, contact/templates/domestic/contact/export-support/includes/visa-and-travel-widget.html
Adds default widgets for guided journey results page.
=> ET-461: Adds default widgets for guided results page

contact/templates/domestic/contact/export-support/guided-journey/step-2.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, core/mixins.py, core/urls.py
Adds Edit functionality to market and products in guided journey
=> ET-461: unguided journey mvp - edit market functionality

core/models.py, domestic/models.py, search/views.py
This ticket fixes a search index error that was occurring in the weekly celery update_index task.
=> GREATUK-877 Fixed search index error

contact/templates/domestic/contact/export-support/guided-journey/step-1.html, contact/templates/domestic/contact/export-support/guided-journey/step-2.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, core/mixins.py, core/views.py
=> ET-461: guided journey mvp - persist data in form fields

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/restricted-market-widget.html, core/views.py
Adds restricted markets functionality
=> ET-461: guided journey mvp - restricted markets

domestic/static/javascript/eventFilters.js
- JS function is not being used on the page . Hence removing .
=> GRTLV-352 : Remove the function as it is no longer needed:

contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html, core/views.py
Adds flags to all market widgets
=> ET-461: guided journey mvp - add flags

international/templates/international/base.html
IGUK-444 Adding html tag to international base template with lang attribute
N/A
=> IGUK-444 Adding html tag to international base template with lang attribute

export_academy/templates/export_academy/includes/event_details_main_content.html
Fixes links that contain spaces
=> Slugify UKEA event type link

contact/templates/domestic/contact/export-support/task-based-category-page.html, contact/templates/domestic/contact/export-support/task-based-sub-category-page.html, core/templatetags/content_tags.py
Persist query params from guided into unguided journey
=> ET-461: guided journey mvp - persist query params into unguided

international/forms.py, international/templates/international/contact.html, international/templates/international/includes/contact_success.html, international/views.py
International contact form update with bot check
N/A
=> IGUK-408 International contact form update with bot check

activitystream/serializers.py, tests/unit/activitystream/test_serializers.py
IGUK-433 Updating EYB user activity stream serializer to support new D and B fields
N/A
=> IGUK-433 Updating EYB user activity stream serializer to support new D and B fields

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/exopps-widget.html
Adds custom rules for exopps widget
To personalise guided journey results page based on user input
=> ET-507: guided journey exopps widget logic

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/visa-and-travel-widget.html
Adds custom rules for visa and travel widget
To personalise guided journey results page based on user input
=> ET-508: guided journey visa and travel widget logic

core/fixtures/sectors-and-sic-sectors.json
Updates fixture file data for sic/sectors
Ensures sectors are compatible with sectors used in wagtail cms
=> ET-510: guided journey - updates sic sector data

config/settings.py
=> fix settings

activitystream/filters.py
Update the HCSAT Filter 
Issues caused in DAG pipeline
=> GRTLV-366: Fix filter for CSAT

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/ukea-widget.html, core/helpers.py, core/views.py
Adds initial solution for displaying ukea events on guided journey
So we can show users the best ukea events for their markets and sectors
=> ET-518: guided journey ukea widget logic

contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html, domestic/templatetags/component_tags.py
Fixes bug with flag icon file name
So users can see correct flags
=> ET-519: guided journey - suggested markets flag bug

contact/templates/domestic/contact/export-support/guided-journey/step-1.html, contact/templates/domestic/contact/export-support/guided-journey/step-2.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/cancel-button.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, core/urls.py
Updates urls for guided journey
So urls are semantic
=> ET-530: guided journey - update urls

contact/templates/domestic/contact/export-support/includes/cancel-button.html
Fixes bug with guided journey edit functionality
=> ET-527: guided journey - fixes bug with edit functionality

contact/templates/domestic/contact/export-support/includes/trade-barriers-widget.html
Updates copy for trade barriers widget
To be consistent with other copy
=> ET-540: guided journey - trade barriers widget copy update

contact/templates/domestic/contact/export-support/includes/exopps-widget.html, contact/templates/domestic/contact/export-support/includes/visa-and-travel-widget.html, core/templatetags/content_tags.py, tests/unit/core/test_templatetags.py
Adds mappings for country slug urls
Not all countries and urls work correctly
=> ET-541: guided journey - country url mappings

config/settings.py, core/helpers.py
AWS S3 client initialisation does not require setting key IDs and Secret keys explicitly
Migration to DBT platform
=> GREATUK-1245 Boto3 S3 client initialization for dbt platform

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/duties-and-taxes-widget.html, contact/templates/domestic/contact/export-support/includes/exopps-widget.html, contact/templates/domestic/contact/export-support/includes/market-promo-widget.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/includes/sector-promo-widget.html, contact/templates/domestic/contact/export-support/includes/visa-and-travel-widget.html, core/views.py
Improves performance of guide journey results page by reducing amount of db requests
Improve user experience
=> ET-550: guided journey - results page performance improvements

contact/templates/domestic/contact/export-support/guided-journey/step-1.html, contact/templates/domestic/contact/export-support/guided-journey/step-2.html, contact/templates/domestic/contact/export-support/guided-journey/step-3.html, contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/includes/skip-button.html
Fixes several small bugs noticed after testing
To make guided journey experience more robust
=> Feature et 552 guided journey bug fixes

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/market-promo-widget.html, contact/templates/domestic/contact/export-support/includes/sector-and-market-card.html, contact/templates/domestic/contact/export-support/includes/sector-promo-widget.html, domestic/helpers.py, domestic/templatetags/component_tags.py
Shows promos based on exporter type
Show must relevant content to users
=> ET-554: guided journey - market/sector promo with goods/service

contact/templates/domestic/contact/export-support/guided-journey/step-4.html, contact/templates/domestic/contact/export-support/includes/goods-widget.html, contact/templates/domestic/contact/export-support/includes/service-widget.html, core/static/javascript/great.digital-self-serve.js
Adds custom tracking for guided journey
So we can analyse user behaviour
=> ET-553: guided journey - custom tracking

contact/templates/domestic/contact/export-support/includes/goods-widget.html, contact/templates/domestic/contact/export-support/includes/service-widget.html
Adds data attributes to accordion/details components
So we can track where user clicks
=> ET-581: guided journey - datalayer accordion tagging

config/env/dev
The env push has broken dev
We need to fix the env so devs can dev
=> Remove APP_ENVIRONMENT from env/dev

contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html
Adds ga tagging fro market guides link
So we can analyse user behaviour
=> ET-586: guided journey - market guides tagging

contact/templates/domestic/contact/export-support/includes/market-widget.html, contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html
Fixes broken link, merges master into develop to fix master/develop phantom commit issue
So tagging works correctly
=> Feature et 586 guided journey market guides tagging fix

contact/templates/domestic/contact/export-support/includes/make-or-do-link.html, contact/templates/domestic/contact/export-support/support.html, core/templates/components/digital_entry_point_homepage_row.html, domestic/templates/domestic/landing_page.html
temporary fix due to caching issue
So guide journey works reliably for users
- [ X] A clear/description pull request messaged added.
=> ET-588: guided journey - caching issue temporary fix

contact/templates/domestic/contact/export-support/includes/make-or-do-form.html, contact/templates/domestic/contact/export-support/support.html, core/static/javascript/great.make-or-do-search.js, core/urls.py, core/views.py
Creates an alternative view for step1 to use a GET request with query params
Sidestep caching issues
=> ET-589: guided journey - step 1 get

core/templates/components/digital_entry_point_homepage_row.html, domestic/templates/domestic/landing_page.html
Puts search box back on homepage
Restore original functionality after caching issue
=> ET-589: guided journey - search box back on homepage

core/templates/microsites/includes/microsite_detail_content.html
Unwanted additional <header> tag in microsite template
=> GRTLV-405 - Remove additional <header> tag from microsite template

domestic/templates/domestic/topic_landing_pages/markets.html
Makes some content and style tweaks to the market guides listing page 
To improve the user experience
=> Minor content changes and UI tweaks

domestic/templates/domestic/topic_landing_pages/markets.html
=> Replace filter market guides copy

config/env.py, config/settings.py, requirements.in, requirements.txt, requirements_test.txt
Server Side tracking for Great
Code added to great-components 
=> Feature greatuk 1279 server side tracking

config/env.py
Set default values for access_key_id and secret_access_key to enable migration to DBT Platform.
=> Hotfix-GREATUK-1325 

contact/forms.py, tests/unit/contact/test_forms.py
Adds ui validation to optional company registration number
Causing some issues with contact form submissions
=> ET-599: contact form - company number validation

.circleci/config.yml, .gitignore, config/env/dev, makefile, requirements.txt, requirements_test.in, requirements_test.txt, tests/browser/steps.py, tests/browser/test_dashboard.py, tests/browser/test_home_page.py, tests/browser/test_lessons.py, tests/browser/util.py
Pytest Allure library is no longer allowed in this repository
This is to mitigate an identified risk with the library
=> GREATUK-1351 Mitigate security risk of using Allure

requirements.in, requirements.txt, requirements_test.txt
Revert server side tracking changes 
We need a separate GA4 property for server side tracking 
=> Revert great-components version

contact/templates/domestic/contact/export-support/guided-journey/step-2.html, core/static/javascript/great.make-or-do-search-enhanced.js
Fixes a couple of bugs found with search enhancements
Experience works correctly for users
=> DSS-7: sic search enhancements - bug fixes

requirements.in, requirements.txt, requirements_test.txt
Updating the env for server side tracking and re-enabling it 
Had to revert previously so as to not corrupt tracking from client side . A new Analytics with different configs were added 
https://analytics.google.com/analytics/web/#/p468737818/reports/dashboard?params=_u..nav%3Dmaui%26_u..pageSize%3D25%26_u.dateOption%3Dtoday%26_u.comparisonOption%3DlastPeriodMdw%26_r..dimension-value%3D%7B%22dimension%22:%22eventName%22,%22value%22:%22page_view%22%7D&r=events-overview-page-view&collectionId=7840207363 
=> Update the server side tracking with new env

international_online_offer/models.py, international_online_offer/views.py
Feature IGUK-188 update breadcrumbs for guide and fix back link on changing triage HQ to find company workflow bug
Change to breadcrumb where guide is linked to be Your expansion guide and fix a back link not going back to change answers after a country HQ change on the triage.
=> Feature IGUK-188 update breadcrumbs for guide and fix back link on changing triage HQ to find company workflow bug

international/context_processors.py, international/templates/international/index.html, international_buy_from_the_uk/templates/buy_from_the_uk/find_a_supplier/profile.html, international_investment/templates/investment/includes/list_item.html, international_investment/templates/investment/opportunity_article.html, international_investment/templates/investment/regions.html, international_investment/templates/investment/sectors.html, international_investment_support_directory/templates/investment_support_directory/find_a_specialist/profile.html, international_online_offer/templates/eyb/triage/find_your_company.html
Feature IGUK-648 small improvements across international
=> Feature IGUK-648 small improvements across international

international_online_offer/helpers.py, international_online_offer/templates/eyb/edit_your_answers.html, international_online_offer/templates/eyb/triage/business_sector.html, international_online_offer/templates/eyb/triage/contact_details.html, international_online_offer/templates/eyb/triage/hiring.html, international_online_offer/templates/eyb/triage/intent.html, international_online_offer/templates/eyb/triage/know_your_setup_location.html, international_online_offer/templates/eyb/triage/location.html, international_online_offer/templates/eyb/triage/spend.html, international_online_offer/templates/eyb/triage/when_want_to_setup.html, international_online_offer/views.py
Feature EYB triage improve saving of changes messaging
So that we show a message on the edit answers page when a user has successfully updated their answers. 
We also update the submit button text on each step of the triage to accurately describe what happens next when a user submits the form.
=> Feature EYB triage improve saving of changes messaging

international_online_offer/templates/eyb/includes/rent.html, international_online_offer/templates/eyb/includes/salary.html, international_online_offer/templates/eyb/triage/find_your_company.html, international_online_offer/templates/eyb/triage/spend.html
Retain focus state when user reloads page after selecting a new drop down value. Added this functionality to please DAC A issue. Its on three pages, spend, salary and rent. 
=> International select retain focus on reload

international/context_processors.py, international_online_offer/templates/eyb/index.html
IGUK-736 and IGUK-745 active state fix on investment opps header and removing alt text on eyb home decorative images
Bug fixes. minor bits
=> IGUK-736 and IGUK-745 active state fix on investment opps header and removing alt on eyb home

domestic/templates/domestic/landing_page.html
Fixes a css issue on mobile
to improve the experience for mobile users
=> fix padding

international_online_offer/core/helpers.py, international_online_offer/models.py, international_online_offer/templates/eyb/guide.html
Bug fixing issue where user signs up with domestic and uses EYB
Sentry was showing an error when the code was trying to use a property on the user object as it was null.
=> Bug fixing issue where user signs up with domestic and uses EYB

international_online_offer/forms.py
Updating error messages on forms across international
UCD found that some error messages needed better context. 
=> Feature IGUK-619 Updating error messages on forms across international

core/views.py
Dont cache guided journey views
You are not able to change product or market when progressing through export support guided journey
=> Dont cache guided journey views

core/views.py
Dont cache export support guided journey
Cannot change product or market of guided journey
=> Bug greatuk 1528 no cache guided journey

international/templatetags/company_filters.py
DAC report found missing hidden labels for inputs in our custom accordion filters on search' across international. Fix to add these hidden labels in and re-structure the html slightly for screen readers
=> Feature IGUK-612 adding legend with hidden label to filters in international

international/url_redirects.py, international_online_offer/helpers.py, tests/unit/international/test_redirects.py
Fixing broken link on EYB guide and adding redirect for legacy international page to EYB
Content have updated the slug on the page in wagtail and the hardcoded link is broken and a legacy page on our international-ui service sees alot of traffic through search engines and we therefore want to ensure it goes to the correct place now via this redirect. Includes all sub pages.
=> Bug IGUK-797 Fixing broken link on EYB guide and adding redirect for legacy international page to EYB

international_buy_from_the_uk/templates/buy_from_the_uk/index.html, international_buy_from_the_uk/templatetags/document_tags.py, requirements.txt, requirements_test.txt
Bug greatuk 1557 fix 5 reasons to buy from the uk r el q4 ie
Document has hard coded url in Great
=> Bug greatuk 1557 fix 5 reasons to buy from the uk r el q4 ie

find_a_buyer/views.py, tests/unit/find_a_buyer/test_views.py
Resolves bug that is preventing users from receiving a company confirmation letter.
=> fix: remove incorrect verification for letters

international_buy_from_the_uk/templates/buy_from_the_uk/index.html
rollback change to document tag
does not work
=> rollback change to document tag

core/validators.py, international_online_offer/core/helpers.py, international_online_offer/forms.py, international_online_offer/templates/eyb/edit_your_answers.html, pii-secret-exclude.txt, tests/unit/core/test_validators.py, tests/unit/international_online_offer/test_forms.py, tests/unit/international_online_offer/test_views.py
Making fullname, role and telephone number optional on EYB triage
Data hub does not require these fields
=> Feature IGUK-667 Making fullname, role and telephone number optional on EYB triage

config/settings.py
Small PR to add new logic to settings.py so local devs can connect to aws via Docker.
The current setup worked when we used CF as we used different secrets. AWS is configured differently.
=> Added new logic for local devs when using aws

sso_profile/templates/exops/is-exops-user-applications.html
Fixes rendering of inline HTML from the ExOpps API
=> Render enguiries inline HTML

international_online_offer/forms.py, international_online_offer/templates/eyb/includes/error_summary.html, international_online_offer/templates/eyb/triage/hiring.html
Fix href on error link text.
Improvement highlighted as part of accessibility audit.
=> IGUK-621 fix error summary link

core/helpers.py, tests/unit/core/test_helpers.py, tests/unit/core/test_views.py, tests/unit/domestic/test_models.py
This PR Fixes the Geo-ip redirection errors encountered during migration.
=> Hotfix greatuk 1607 fix geoip redirect code

core/static/javascript/dit.tagging.js
Update progress when video plays 
Update progress when video plays 0, 25, 50,75, 100 percent 
=> Feature grtlv 424 update video percent as video progresses

config/settings.py, core/middleware.py, core/tasks.py
Adding a new middleware to be run before all views to send GA4 server side and using a celery task to delay
Previous implementation wasn't capturing across all the Views , hence adding it to middleware
Server side UAT GA
https://analytics.google.com/analytics/web/?authuser=0#/p470346173/reports/dashboard?params=_u..nav%3Dmaui%26_u.comparisonOption%3Ddisabled%26_u.date00%3D20241213%26_u.date01%3D20241216&r=lifecycle-engagement-overview&ruid=lifecycle-engagement-overview,life-cycle,engagement&collectionId=life-cycle
=> Feature grtlv 464 server side tracking

requirements.in, requirements.txt, requirements_test.txt
Bump Django to 4.2.19
Vunerabilities
=> Bump Django to 4.2.19

core/templates/components/great/migration_notice_banner.html
Added downtime banner
For dir-api database upgrade
=> Added downtime banner

config/settings.py, search/templates/search_opensearch.html, search/templates/search_preview_opensearch.html, search/templatetags/search.py
This ticket refactors the Opensearch results page to display enhanced Titles, Descriptions, and Content Types.
=> Refactor Opensearch results page

config/settings.py, tests/unit/activitystream/test_serializers.py
This ticket enables the auto update of the search index.
=> Enable auto update on search index

domestic/templates/domestic/blocks/article_snippet.html
need to load wagtail filters before using richtext filter
getting invalid filter for richtext filter
=> need to load wagtail filters before using richtext filter

core/templatetags/content_tags.py, domestic/templates/domestic/includes/streamfield.html, requirements.txt, requirements_test.txt
issue with richtextfields used in Content Modules snippets
Cant use internal links in Richtextfields in Content Module snippets
=> Fix richtest issue with Content Modules

search/templates/search_opensearch.html
This ticket enhances the fallback description choices for Opensearch search results.
=> feature: update search description fallback templates

core/management/commands/copy_site_pages.py
First pass at management command to copy site pages. This is intended to be a one-off command so SHOULD NOT be made a periodic task.
For local testing:
`python manage.py copy_site_recursive --source <source site domain> --dest <destination site domain>`
This command will be used to migrate from great.gov.uk to business.gov.uk
=> GREATUK-1711 Management command to copy great pages to bgs site

domestic_growth/models.py, domestic_growth/views.py
Disables caching from bgs triage and guide pages
Issue when changing postcode in triage step and returning to guide page
=> BGST-174: guide model - disable caching

international_online_offer/templates/eyb/guide-dynamic.html, international_online_offer/templates/eyb/includes/dynamic-guide/rent_data.html
BGST-333 Focus DDL on change when reloading page EYB guide
Accessibility 
=> BGST-333 Focus DDL on change when reloading page EYB guide

core/templates/captcha/includes/js_v3.html
Fixing ReCaptcha on UKEF help form
=> Improve query selector for ReCaptcha field

core/templatetags/content_tags.py, domestic/templatetags/component_tags.py, domestic_growth/constants.py, domestic_growth/models.py, domestic_growth/templates/guide-child.html, domestic_growth/templates/includes/_render-snippet.html, domestic_growth/templates/includes/dynamic-snippets/_finance-and-support.html, domestic_growth/templates/includes/dynamic-snippets/_find-a-grant.html, domestic_growth/templates/includes/dynamic-snippets/_ita.html, domestic_growth/templates/includes/dynamic-snippets/_placeholder-snippet.html
Adds logic for rendering BGS guide page snippets which are dynamic
Allow some content to change based on triage answers
Note: Some hardcoded values will be removed once triage work is integrated
=> BGST-176: content snippet - dynamic rendering solution

config/env.py, config/settings.py, core/constants.py, core/helpers.py, core/templates/components/great/migration_notice_banner.html, core/templatetags/bgs_tags.py, requirements.txt, requirements_test.txt, tests/unit/core/test_templatetags.py
Add Banner to all Business Growth pages - also feature flagged
To help people see when they are on new Business Growth pages
=> Feature greatuk 1743 new site banner

core/management/commands/obsfucate_personal_details.py, core/tasks.py, tests/unit/core/test_tasks.py, tests/unit/international_online_offer/factories.py
Management Command to Obsfucate Personal Data
Required in hotfix branch to stop "sensitive data" displaying in Hotfix env
=> Management Command to Obsfucate Personal Data

core/management/commands/obsfucate_personal_details.py
When obsfucating emails add count to name
Emails are unique
=> Emails are unique

core/management/commands/obsfucate_personal_details.py
=> refactor email count

domestic_growth/admin.py, domestic_growth/templates/admin/csv-upload-form.html, domestic_growth/templates/admin/domestic-growth-content-changelist.html, tests/unit/domestic_growth/test_admin.py
Adds functionality to enable `DomesticGrowthContent` Wagtail Snippets to be created or modified from an uploaded .csv file.
- Loosely based on [this recipe](https://books.agiliq.com/projects/django-admin-cookbook/en/latest/import.html) with some additional checks for file size and type. 
- Uses an `InMemoryUploadedFile` [ref](https://docs.djangoproject.com/en/5.0/ref/files/uploads/#django.core.files.uploadedfile.InMemoryUploadedFile) so we do not allow uploads of files > 1Mb. This is an arbitrary limit however, for context the required .csv for BGS launch contains 127 snippets and is 30KB.
Necessary for BGS launch. Previous approach relied on committing the .csv file to code and running an ingestion management command. This was laborious when changes were required. 
1. Navigate to …
=> add csv upload for DomesticGrowthContent to django admin

domestic/templates/domestic/finance/lead_generation_form/base.html, domestic/templates/domestic/finance/lead_generation_form/success.html, domestic/urls.py, domestic/views/ukef.py
Update the page https://www.great.gov.uk/get-finance/your-details/  and https://www.great.gov.uk/get-finance/contact/thanks/ to remove the old breadcrumbs 
We are using the design system breadcrumbs which is a part of the base.html page we need to remove the old one .
Before 
After
=> GRTLV-685: Remove the old breadcrumbs

search/views.py
Bugfix to resolve error on pagination count.
=> Fix bug on search pagination count

international_online_offer/tasks.py
Change EYB rescore job to only run on records younger than six months
Stakeholders only want newer records updated
=> Change EYB rescore job to only run on records younger than six months

international_online_offer/templates/eyb/guide-new.html
This PR addresse the dynamic guide rounding off value "Setting up a base in the uk" section
This change requires as the decimals are more and not properly readable.
=> Feature IGUK-975 Add rounding off value

core/management/commands/copy_site_pages.py
Great international pages should no longer be sub pages in domestic page tree in BGS site
New BGS site content design structure needs it
=> Feature greatuk 1752 copy international folder to bgs tree

domestic_growth/templates/guide.html
=> Explicitly pass support data to snippet

international_online_offer/views.py
Fixes a bug in the International Online offer redirect page.
=> bug: fix international online offer login redirect issue

international_online_offer/management/commands/delete_international_online_offer_data.py
We have user requests asking us to delete their data on Great. Most of the data can be deleted by using an existing management command archive_users in directory_sso. Some data is stored standalone and will need to be deleted as well .
This management command allows us to delete the data stored for EYB and Triage data for a user.
=> Add a management command to delete EYB and Triage data for users

international/templates/international/contact.html, international/templates/international/contact_success.html, international_online_offer/models.py, international_online_offer/templates/eyb/bci.html, international_online_offer/templates/eyb/triage/business_sector.html
Feature iguk 997 dac fixes
Pass DAC
- [] Checked for potential security vulnerabilities
=> Feature iguk 997 dac fixes

core/context_processors.py, domestic_growth/constants.py, domestic_growth/models.py, domestic_growth/templates/home.html
Removes dynamic urls from header/footer which is causing an issue in prod
Restore prod functionality
=> BGST-392: removes dynamic urls from header/footer

core/templates/microsites/includes/microsite_detail_content.html
Correct load tags order
Load statement after code
=> Correct load tags order

domestic_growth/helpers.py, great_design_system/forms/fields.py, great_design_system/tests/test_forms/expected_html/char_field.html, great_design_system/tests/test_forms/expected_html/typed_date_field.html, great_design_system/tests/test_forms/test_fields/test_char_field.py, great_design_system/tests/test_forms/test_fields/test_charfield.py, great_design_system/tests/test_forms/test_fields/test_email_field.py, great_design_system/tests/test_forms/test_fields/test_typed_date_field.py, search/templates/search_feedback.html, search/templates/search_opensearch.html
=> new render test

config/url_redirects.py, core/context_processors.py, domestic_growth/constants.py, domestic_growth/urls.py, tests/unit/core/test_templatetags.py, tests/unit/domestic_growth/test_helpers.py, tests/unit/domestic_growth/test_views.py
=> Update support url

core/templates/components/inline_feedback/negative_feedback.html, core/templates/components/inline_feedback/positive_feedback.html, domestic_growth/static/js/helpers.js, domestic_growth/templates/dynamic-guide-child.html, domestic_growth/templates/guide-child.html, domestic_growth/templates/guide.html, domestic_growth/templates/includes/base.html
More design QA amends for Guide pages
Fix outstanding issues
=> BGST-377: Guide qa amends - P2s

great_design_system/forms/widgets.py, international_online_offer/templates/eyb/bci.html, international_online_offer/views.py
Bugs with EYB BCI page title and drop downs not showing selected value when using DS component
DAC fixes
- [] Frontend assets have been re-compiled
=> Bugs with EYB BCI page title and drop downs not showing selected value when using DS component

core/helpers.py, core/templatetags/bgs_tags.py
Add sentry log capture to debug production Campaign site menu links 
Page links must be for the domain user is using in a multi-site setup so they are not navigated to a different site.
=> GREATUK-1769 Add Telemetry to debug menu

international_online_offer/models.py, international_online_offer/templates/eyb/guide-new.html
Bug fix for DAC on EYB guide making link context better
DAC
=> Bug fix for DAC on EYB guide making link context better

core/context_processors.py
=> Change bgs footer market text to market guides

requirements.in, requirements.txt, requirements_test.txt
Patch xhtml2pdf
Vulnerability in previous version 
=> upgrade dependency

domestic_growth/templates/existing-business/triage-currently-export.html, domestic_growth/templates/existing-business/triage-location.html, domestic_growth/templates/existing-business/triage-sector.html, domestic_growth/templates/existing-business/triage-turnover.html, domestic_growth/templates/existing-business/triage-when-set-up.html, domestic_growth/templates/starting-a-business/triage-location.html, domestic_growth/templates/starting-a-business/triage-sector.html
Updated triage page titles.
Mentioned as part of BGS QA.
=> BGST-375 - bgs triage page title updates

international_online_offer/views.py
feature IGUK-1001 EYB check answers support for optionals
So that a link appears when an optional value is missing taking users to the page where they can enter the missing info
=> feature IGUK-1001 EYB check answers support for optionals

international/forms.py, international/templates/international/contact.html, international/templates/international/includes/contact_success.html
Small content change for support forms 
To support move to one support form for Business Growth
=> Amend content for support forms

international/templates/international/includes/form_field.html, international_online_offer/templates/eyb/login.html
feature IGUK-770 updating EYB login UI
Jon asked for this
=> feature IGUK-770 updating EYB login UI

international/forms.py, international/templates/international/contact.html, international/views.py
Updates support form content
To work towards one support form
=> More content changes

domestic_growth/templates/home.html, domestic_growth/templates/includes/_render-snippet.html, domestic_growth/templates/includes/_talk-to-an-ita.html
Fixes a few minor issues noticed during testing for BGS Guide and homepage
Show correct urls and content
=> BGST-381: Fixes issues raised from testing

international/templates/international/contact.html
=> Add no follow no index to site-help

core/models.py, domestic_growth/templates/includes/_business-support-service.html
Fixes develop into master conflicts
Enable release PRs
=> Fixes develop into master conflicts

international_online_offer/models.py
This PR addresses to show both Imperial and Metric in rent data 
Feature IGUK-990 Show rent data in both imperial and metric
=> Add both imperial and metric units

.copilot/image_build_run.sh
Small amendment to [this PR](https://github.com/uktrade/great-cms/pull/4088) - refer to link for full details.
=> BGST-409 small amendment for failing build fix

international/templates/international/index.html
Reverting invest index card update 
Breaking change
=> bug IGUK-1008 reverting invest index card update

international_investment/templates/investment/sectors.html
feature IGUK-1010 using thumbnail on sectors page
Marketing want separate images used for the thumb and the article image
=> feature IGUK-1010 using thumbnail on sectors page

international_online_offer/templates/eyb/triage/company_details.html
This PR addresses to fix styling for label and value
=> Fix styling

domestic/views/campaign.py
Arabic pages were not in the same site_root as the English pages . site.root_page points to default locale 
Updating to change root of site page based on locale .
=> Update the root site based on locale

config/settings.py, domestic_growth/static/js/bss-webchat.js, domestic_growth/templates/guide-child.html, domestic_growth/templates/guide.html, domestic_growth/templates/includes/_business-support-service.html
Implements bss webchat on guide pages for England based businesses
Chatbot like functionality required bgs
=> BGST-425: bss webchat

domestic_growth/helpers.py, domestic_growth/models.py, domestic_growth/views.py
1. Remove redundant code as per comments on [this PR](https://github.com/uktrade/great-cms/pull/4064)
2. Log exceptions to Sentry
3. Fix bug whereby opening a share link and sending the guide via 'Save and share these pages' functionality without navigating to another page caused an error
Tidy code / preparation for BGS launch
Bug can be replicated by:
1. Complete triage
2. Email Guide
3. Open link to Guide in email
4. Email Guide without navigating to another page
5. Error thrown as cannot get `triage_uuid`
=> BGST-409 remove redundant code / log exceptions / small bug fix

domestic_growth/static/js/bss-webchat.js, domestic_growth/templates/includes/_business-support-service.html
Copy amends for bss webchat
improve copy
=> BGST-425: BSS webchat copy amends

config/settings.py
Fixes csp issues on bss webchat
bss webchat not loading
=> BGST-425: fix csp issues on bss webchat

config/env.py
Letter template should be email template - temp fix
Wrong template created
=> Letter template should be email template - temp fix

domestic_growth/fixtures/trade_associations.json
Fixes broken trade association link
Accessibility issue
=> BGST-406: Fix broken trade association link

core/templatetags/content_tags.py, international/templatetags/company_filters.py, international_investment/templates/investment/includes/list_item.html, international_investment/templates/investment/index.html, tests/unit/core/test_templatetags.py
New simple tag to strip domain from any link deemed as internal
stop treating high environments as external links.
=> Bug greatuk 1977 create internal link

international_investment/templates/investment/index.html, international_online_offer/models.py
=> fixed hardcoded url

international_investment/models.py
Bug fix for duplicate investment opportunities showing due to multi-site
Cause
=> Bug fix for duplicate investment opportunities showing due to multi-site

core/management/commands/update_content.py
=> alter string replacement argument

config/env.py, tests/unit/export_academy/test_tasks.py, tests/unit/export_academy/test_views.py
Fix BGS Notify template Ids
2 are wrong
=> Feature greatuk 1795 confirm email template

domestic_growth/helpers.py, domestic_growth/models.py, domestic_growth/templates/includes/_email-guide-form.html, tests/unit/domestic_growth/test_helpers.py
Removes potential threat of bot submissions to the email guide form by only displaying for users who have completed the triage.
Prevent bot form submissions
=> BGST-432: Threat modeling - email guide

config/settings.py, core/templates/components/great/migration_notice_banner.html
This ticket adds a banner alerting users of the changeover to the business.gov website.
=> Add business.gov banner

core/templates/core/includes/submit_button.html, domestic/templatetags/component_tags.py, domestic_growth/helpers.py, domestic_growth/models.py, domestic_growth/templates/dynamic-guide-child.html, domestic_growth/templates/guide-child.html, domestic_growth/templates/guide.html, domestic_growth/templates/home.html, domestic_growth/templates/includes/_email-guide-form.html, domestic_growth/templates/includes/_growth-hub.html, search/templates/search_opensearch.html, tests/unit/domestic/test_templatetags.py, tests/unit/domestic_growth/test_helpers.py
Adds GA datalayer tracking and data attributes for BGS pages
Allow user journeys to be tracked thoroughly in GA
=> BGST-380: Datalayer tracking

core/context_processors.py, core/templates/core/business_growth_contact.html, core/templates/core/business_growth_contact_sent.html, core/urls.py, core/views.py
This PR fixes some of the issues that were highlighted by QA and also updates the url for site help to the correct value. 
To get contact form ready for the bgs release
confluence for amends:
https://uktrade.atlassian.net/wiki/spaces/Great/pages/edit-v2/4773478466
=> CSS amends and url update

core/templates/core/business_growth_contact.html
Quick patch for a bad git merge which removed the new Ts and Cs check box
to fix the contact form 
=> reinsert terms and conditions field

domestic_growth/static/js/bss-webchat.js
Updates bss webchat JS script
To use latest version of the script provided
=> BGST-429: Update bss webchat script

domestic/templates/domestic/finance/lead_generation_form/base.html
Make the Label align centre to the checkbox
=> Update the style on Uk export finance

core/context_processors.py
P2 issues raised for incorrect urls in header nav for - dashboard, profile and export plan
Take users to correct pages
=> GREATUK-2054: Wrong urls for dashboard, profile and export plan

core/management/commands/update_redirects.py
Command to bulk upload redirect URLs. This based on the initial work started [here](https://github.com/uktrade/great-cms/pull/4147) 
This command is expected to run during switchover from great.gov.uk to business.gov.uk
=> GREATUK-1818 bulk redirect map upload management command

core/models.py, core/urls.py
Campaign should now be under root folder 
In BGS Campaign should be under root and should be accessed via /campaign/<name>
**English page** 
**Toggle**
**Arabic Page**
=> GREATUK-1759 - Campaign now under root

core/context_processors.py
Changes "services" to "resources"
Match new url structure
=> GREATUK-2106: Changes services to resources

international_buy_from_the_uk/templates/buy_from_the_uk/find_a_supplier/contact.html, international_buy_from_the_uk/views.py
bug GREATUK-2011 buy from the uk contact company success fix
Moving site-help from international to core broke the success page. Followed fix on ISD to solve
=> bug GREATUK-2011 buy from the uk contact company success fix

international/templates/international/index.html
bug GREATUK-1984 invest regions link fix
Using the an object instead of url for regions link
=> bug GREATUK-1984 invest regions link fix

core/management/commands/update_content.py
Handle ListValue content type and just report and continue unhandled content types
ListValue content type added
Just report unhandled content types
=> Feature greatuk 2061 handle listvalue

core/models.py
Reverts previous bugfix which in turn caused a bug on Hotfix.
=> bug: revert link bugfix

international_online_offer/templates/eyb/signup.html
bug-GREATUK-email-missing-breaks-signup-page-eyb
No check on email was done so page fails when accessed from verification code email link.
=> bug-GREATUK-email-missing-breaks-signup-page-eyb

core/templates/microsites/includes/microsite_detail_content.html
Clicking the logo on a microsite should take the user to the homepage, not the href of the first menu item (as current).
Desired user experience.
=> GREATUK-2009 microsite logo href

core/helpers.py, core/templatetags/bgs_tags.py
Feature GREATUK-1802 removing old info logs causing performance issues with sentry. 10m logs +
SRE highlighting we're throwing a lot of logs at sentry and its causing performance issues.
=> Feature GREATUK-1802 removing old info logs causing performance issues with sentry

core/constants.py, core/helpers.py, core/views.py
Update the Guided Journey URL categoties 
Update the URLs based on the Site 
**ON BGS** 
**ON GREAT**
=> Update the URLS based on the site

international/url_redirects.py, tests/unit/international/test_redirects.py
Fix 404 error on Buy From the UK contact page.
BGS launch QA.
=> GREATUK-2118 - form success error link

core/management/commands/update_content.py
Bug greatuk 2132 dry run reporting and checking for events.great.gov.uk
Bug fix
=> Bug greatuk 2132 dry run reporting

core/templates/core/steps.html
Reverts learn to export bugfix
=> chore: revert bugfix

domestic_growth/templates/includes/_business-support-service.html
Add privacy wording at bottom of web chat.
Necessary for BGS launch.
=> GREATUK-2012 add privacy wording to webchat

domestic_growth/forms.py, domestic_growth/templates/includes/_email-guide-form.html, tests/unit/domestic_growth/test_forms.py, tests/unit/domestic_growth/test_models.py
Add Tnc and Policy to triage 
As a part of moving to public task we need to update place where personal information is entered 
=> Add TnC link to Triage 

domestic_growth/static/js/bss-webchat.js, domestic_growth/templates/includes/_business-support-service.html
Update wording of BGS Chat.
Small changes received after merge of [this PR](https://github.com/uktrade/great-cms/pull/4213).
=> GREATUK-2012 - amend bgs chat wording

core/templates/components/great/migration_notice_banner.html
=> GREATUK-2178 update banner to 9th June

domestic/templates/domestic/country_guide.html
Fix vat-in-uk link
Note: In Wagtail this article had a hash appended to the slug, i.e. the slug was `vat-in-eu-cc9a30c3` this has been removed in Wagtail.
Raised as QA item
=> GREATUK-2060 fix vat-in-eu link

contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html
Add conditional urls to hardcoded market guide pages on export guides
=> GREATUK-2197 - Add conditional for bgs for market guides link

contact/templates/domestic/contact/export-support/guided-journey/base.html
Adds additional argument to export support breadcrumb filter
Guide journey pages affected by previous code change
=> GREATUK-2189: pass extra argument to filter

core/templates/components/great/migration_notice_banner.html
feature GREATUK-2213 changing release banner text
We need more time to release.
=> feature GREATUK-2213 changing release banner text

international_buy_from_the_uk/templates/buy_from_the_uk/index.html
Adding trailing slash for e book on buy from uk
=> Adding trailing slash for e book on buy from uk

contact/templates/domestic/contact/export-support/includes/suggested-markets-widget.html
Fix Markets Read More Link
Does not work 
djlint reformated
=> Fix Markets Read More Link

core/helpers.py, domestic/models.py, tests/unit/core/test_helpers.py, tests/unit/domestic/test_models.py
Adding sentry log to debug international redirect
debug international redirect
=> GREATUK-2252 add sentry telemetry for prod
